"""Public lookup of the published portal terms version before activation (AE34, AD03-01).

``GET /portal/public/terms`` is the only unauthenticated read of the consent policy. It
answers with the published version of exactly one tenant and nothing else:

* the tenant is named by ``?tenant=`` (slug or tenant id, the id is part of the invitation
  code) or, without the parameter, by the portal host (``X-Portal-Host`` or ``Host``, 3.3);
* an unknown tenant, a malformed name, an inactive tenant and a tenant without a published
  version all answer the same 404, so the endpoint reveals neither which tenants exist nor
  which have published terms (no tenant enumeration, rule 0.1.13);
* no tenant name, id, list or text is returned; the text of the terms is not generated by the
  platform (OPEN_QUESTIONS AC06-03);
* the request rate limit of anonymous callers applies (``core.ratelimit``, per client address).
"""

import re
import uuid

from fastapi import Request
from pydantic import BaseModel
from sqlalchemy import select

from mhvp.contacts import consent_rules
from mhvp.core.auth.principal import resolve_host_tenant, sessions
from mhvp.core.db.tenancy import platform_transaction, tenant_transaction
from mhvp.core.problems import ErrorCodes, ProblemError
from mhvp.platform.models import Tenant, TenantDomain, TenantStatus

_SLUG = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")
_ID = re.compile(r"^(?:[0-9a-f]{32}|[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12})$")

EVIDENCE = ["accepted_at", "terms_version", "client_hash"]


class PortalPublicTermsOut(BaseModel):
    """Published version only. ``evidence`` names what the acceptance records (time, version,
    keyed hash of the client address, never the address itself)."""

    terms_version: str
    acceptance: str = "textform"
    evidence: list[str] = EVIDENCE


def not_found() -> ProblemError:
    # One generic answer for every miss; the detail never names the tenant or the reason.
    return ProblemError(ErrorCodes.RESOURCE_NOT_FOUND)


async def _tenant_by_name(request: Request, name: str) -> uuid.UUID | None:
    value = name.strip().lower()
    async with platform_transaction(sessions(request)) as session:
        if _ID.match(value):
            row = await session.scalar(select(Tenant).where(Tenant.id == uuid.UUID(value)))
        elif _SLUG.match(value):
            row = await session.scalar(select(Tenant).where(Tenant.slug == value))
        else:
            return None
        if row is None or row.status != TenantStatus.ACTIVE:
            return None
        found: uuid.UUID = row.id
        return found


async def _tenant_by_host(request: Request) -> uuid.UUID | None:
    forwarded = (request.headers.get("x-portal-host") or "").split(":")[0].strip().lower()
    tenant_id: uuid.UUID | None
    if forwarded:
        async with platform_transaction(sessions(request)) as session:
            tenant_id = await session.scalar(
                select(TenantDomain.tenant_id).where(TenantDomain.host == forwarded)
            )
    else:
        tenant_id = await resolve_host_tenant(request)
    if tenant_id is None:
        return None
    async with platform_transaction(sessions(request)) as session:
        row = await session.get(Tenant, tenant_id)
    if row is None or row.status != TenantStatus.ACTIVE:
        return None
    return tenant_id


async def published_terms(request: Request, tenant: str | None) -> PortalPublicTermsOut:
    tenant_id = (
        await _tenant_by_name(request, tenant)
        if tenant is not None and tenant.strip()
        else await _tenant_by_host(request)
    )
    if tenant_id is None:
        raise not_found()
    async with tenant_transaction(sessions(request), tenant_id) as session:
        policy = await consent_rules.load_policy(session)
    if policy.portal_terms_version is None:
        raise not_found()
    return PortalPublicTermsOut(terms_version=policy.portal_terms_version)
