"""Rule engine stage 1: context per event, action execution and the beat processing loop.

Processing (``process_tenant``): the beat job reads new rows of ``domain_event`` since the
tenant's watermark (ordered by ``occurred_at, id``, with a short lag so that a transaction
that commits late is not skipped), evaluates every active rule whose trigger matches the
event type and executes the actions of matching rules. Each rule and event pair runs at most
once (``automation_run`` unique constraint) and inside a savepoint, so one failing rule
neither blocks the others nor the watermark. Events written by rule actions carry the
``automation`` marker and never trigger a rule again (depth 1).

Rule actions never post, pay, approve or send mail (rules 0.1.6, 0.1.7). Stage 2 (A39) adds
a signed outbound webhook, e-mail and letter drafts and AI tasks (proposal only), plus the
schedule trigger (``process_schedules``: one run per rule and due moment).
"""

import base64
import json
import logging
import time
import uuid
from datetime import UTC, date, datetime, timedelta
from typing import Any

import httpx
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from mhvp.automation.models import (
    DELIVERY_DEAD,
    DELIVERY_PENDING,
    DELIVERY_SUCCEEDED,
    RUN_STATUS_DRY_RUN,
    RUN_STATUS_EXECUTED,
    RUN_STATUS_FAILED,
    SCHEDULE_EVENT_TYPE,
    TRIGGER_SCHEDULE,
    WEBHOOK_MAX_ATTEMPTS,
    WEBHOOK_RETRY_SCHEDULE_SECONDS,
    AutomationRule,
    AutomationRun,
    AutomationWatermark,
    AutomationWebhookDelivery,
)
from mhvp.automation.rules import (
    RELATED_FIELDS,
    automation_marker,
    evaluate,
    is_automation_event,
    normalise,
    related_groups,
    render,
    resolve_value,
)
from mhvp.automation.schedule import SCHEDULE_TZ, previous_due, window_event_id
from mhvp.automation.schemas import (
    Action,
    AiTaskAction,
    AssignRecordAction,
    CreateTaskAction,
    CreateTicketAction,
    LetterDraftAction,
    MailDraftAction,
    NotifyAction,
    SetTicketFieldAction,
    WebhookAction,
    parse_actions,
)
from mhvp.core import crypto
from mhvp.core.config import Settings, get_settings
from mhvp.core.events import DomainEvent, emit
from mhvp.core.numbering import next_number
from mhvp.tickets.models import (
    Priority,
    Team,
    Ticket,
    TicketEvent,
    TicketSource,
    TicketTemplate,
)
from mhvp.workspace.services import notify

log = logging.getLogger(__name__)

# Events younger than this are left for the next run (late commits with an older
# ``occurred_at``, see module docstring).
PROCESS_LAG = timedelta(seconds=5)
BATCH_LIMIT = 500
NOTIFICATION_KIND = "automation"
# A83: letters generated by a rule are drafts; category code and notice printed on the PDF.
DRAFT_CATEGORY_CODE = "entwurf"
DRAFT_CATEGORY_NAME = "Entwurf"
DRAFT_NOTICE = "ENTWURF, automatisch erzeugt am {date} durch Regel {rule}, nicht versendet"
WEBHOOK_TIMEOUT_SECONDS = 10.0
# Private key of a webhook action result between ``_webhook`` and ``_record`` (never stored).
PENDING_DELIVERY_KEY = "_pending_delivery"
TICKET_CONTEXT_FIELDS: tuple[str, ...] = (
    "id",
    "number",
    "property_id",
    "unit_id",
    "contact_id",
    "template_id",
    "category",
    "topic",
    "title",
    "public_description",
    "status",
    "priority",
    "assignee_user_id",
    "team_id",
    "initiator_contact_id",
    "source",
    "sla_due_at",
    "created_at",
)


class ActionError(Exception):
    """An action could not be executed (recorded in the run, rule continues with the next event)."""


# --- context -------------------------------------------------------------------------------


def ticket_context(ticket: Ticket, *, now: datetime | None = None) -> dict[str, Any]:
    """Ticket fields plus derived condition fields (M9-08): ``age_days`` (whole days since
    creation) and ``due_in_days`` (whole days until ``sla_due_at``, negative once overdue),
    so a rule condition can read ``entity.age_days`` (Ticketalter) or ``entity.due_in_days``
    (Fristbezug, Tage vor Termin) with the existing ``gt``/``lt`` operators. ``None`` when
    the ticket has no deadline."""
    context = {k: normalise(getattr(ticket, k)) for k in TICKET_CONTEXT_FIELDS}
    now = now or datetime.now(UTC)
    context["age_days"] = (now - ticket.created_at).days
    context["due_in_days"] = (
        (ticket.sla_due_at - now).days if ticket.sla_due_at is not None else None
    )
    return context


async def message_context(session: AsyncSession, message: Any) -> dict[str, Any]:
    """Fields of a mail for rule conditions (Lern-Workflow, rule M9-11): sender address and
    domain in lower case, assignment fields, the ticket of the mail and ``opens_ticket`` (the
    mail is the first inbound mail of its ticket, i.e. the ticket was opened by it; a reply
    joining an existing ticket is not)."""
    from mhvp.communication.models import Message

    address = (message.from_address or "").strip().lower() or None
    opens_ticket = False
    if message.ticket_id is not None and message.direction == "in":
        first = await session.scalar(
            select(Message.id)
            .where(Message.ticket_id == message.ticket_id, Message.direction == "in")
            .order_by(Message.created_at, Message.id)
            .limit(1)
        )
        opens_ticket = first == message.id
    return {
        "id": str(message.id),
        "direction": message.direction,
        "from_address": address,
        "from_domain": address.rsplit("@", 1)[1] if address and "@" in address else None,
        "mailbox_id": normalise(message.mailbox_id),
        "contact_id": normalise(message.contact_id),
        "property_id": normalise(message.property_id),
        "ticket_id": normalise(message.ticket_id),
        "opens_ticket": opens_ticket,
        "subject": message.subject,
    }


async def build_context(
    session: AsyncSession,
    *,
    type: str,
    entity_type: str,
    entity_id: uuid.UUID | None,
    payload: dict[str, Any] | None,
    actor_user_id: uuid.UUID | None = None,
    entity_override: dict[str, Any] | None = None,
    related: set[str] | None = None,
    tenant_id: uuid.UUID | None = None,
) -> dict[str, Any]:
    """Evaluation context: event fields plus the current fields of a ticket entity and, for
    the groups in ``related`` (A81), the linked property, unit, contact and contract."""
    entity: dict[str, Any] = dict(entity_override or {})
    if entity_type == "ticket" and entity_id is not None and not entity_override:
        ticket = await session.get(Ticket, entity_id)
        if ticket is not None:
            entity = ticket_context(ticket)
    elif entity_type == "message" and entity_id is not None and not entity_override:
        from mhvp.communication.models import Message

        message = await session.get(Message, entity_id)
        if message is not None:
            entity = await message_context(session, message)
    context = {
        "type": type,
        "entity_type": entity_type,
        "entity_id": str(entity_id) if entity_id else None,
        "actor_user_id": str(actor_user_id) if actor_user_id else None,
        "payload": {k: normalise(v) for k, v in (payload or {}).items()},
        "entity": entity,
    }
    if related:
        await enrich_context(session, context, related, tenant_id=tenant_id)
    return context


async def context_for_event(
    session: AsyncSession, event: DomainEvent, related: set[str] | None = None
) -> dict[str, Any]:
    return await build_context(
        session,
        type=event.type,
        entity_type=event.entity_type,
        entity_id=event.entity_id,
        payload=event.payload,
        actor_user_id=event.actor_user_id,
        related=related,
        tenant_id=event.tenant_id,
    )


# --- related master data (A81) ------------------------------------------------------------


def _id_from(context: dict[str, Any], *paths: str) -> uuid.UUID | None:
    """First UUID found at ``paths`` in the entity, the payload or the event itself."""
    for path in paths:
        source, _, key = path.partition(".")
        value = (context.get(source) or {}).get(key) if source else context.get(key)
        if value in (None, ""):
            continue
        try:
            return uuid.UUID(str(value))
        except ValueError:
            continue
    return None


def _pick(row: Any, fields: tuple[str, ...]) -> dict[str, Any]:
    return {k: normalise(getattr(row, k, None)) for k in fields}


def contract_status(start: date, end: date | None, termination: date | None, today: date) -> str:
    """Derived status of a contract at ``today`` (deterministic, no stored field)."""
    if start > today:
        return "future"
    if end is not None and end < today:
        return "ended"
    if termination is not None:
        return "terminated"
    return "active"


async def enrich_context(
    session: AsyncSession,
    context: dict[str, Any],
    groups: set[str],
    *,
    tenant_id: uuid.UUID | None = None,
    today: date | None = None,
) -> dict[str, Any]:
    """Add ``property``, ``unit``, ``contact`` and ``contract`` (only the requested groups)
    to the context from the ids of the entity or the payload. One query per group; a missing
    link yields an empty group so every field resolves to ``None``. Rows of another tenant
    are never read (RLS plus an explicit tenant filter)."""
    from mhvp.contacts.models import Contact, ContactTag, ContactTagLink, PartyMember
    from mhvp.contracts.models import Contract
    from mhvp.properties.models import Property, Unit

    def scoped(query: Any, model: Any) -> Any:
        return query.where(model.tenant_id == tenant_id) if tenant_id is not None else query

    for group in groups:
        if group in RELATED_FIELDS:
            context.setdefault(group, {})
    entity_type = context.get("entity_type")
    property_id = _id_from(
        context,
        "entity.property_id",
        "payload.property_id",
        *(("entity_id",) if entity_type == "property" else ()),
    )
    unit_id = _id_from(
        context,
        "entity.unit_id",
        "payload.unit_id",
        *(("entity_id",) if entity_type == "unit" else ()),
    )
    contact_id = _id_from(
        context,
        "entity.contact_id",
        "entity.initiator_contact_id",
        "payload.contact_id",
        *(("entity_id",) if entity_type == "contact" else ()),
    )
    unit: Unit | None = None
    if ("unit" in groups or "contract" in groups) and unit_id is not None:
        unit = await session.scalar(scoped(select(Unit).where(Unit.id == unit_id), Unit))
        if unit is not None and property_id is None:
            property_id = unit.property_id
    if "unit" in groups and unit is not None:
        context["unit"] = _pick(unit, RELATED_FIELDS["unit"])
    if "property" in groups and property_id is not None:
        prop = await session.scalar(
            scoped(select(Property).where(Property.id == property_id), Property)
        )
        if prop is not None:
            context["property"] = _pick(prop, RELATED_FIELDS["property"])
    if "contact" in groups and contact_id is not None:
        contact = await session.scalar(
            scoped(select(Contact).where(Contact.id == contact_id), Contact)
        )
        if contact is not None:
            tags = list(
                await session.scalars(
                    scoped(
                        select(ContactTag.name)
                        .join(ContactTagLink, ContactTagLink.tag_id == ContactTag.id)
                        .where(ContactTagLink.contact_id == contact.id)
                        .order_by(ContactTag.name),
                        ContactTagLink,
                    )
                )
            )
            data = _pick(contact, RELATED_FIELDS["contact"])
            data["roles"] = sorted(str(normalise(r)) for r in (contact.roles or []))
            data["tags"] = tags
            context["contact"] = data
    if "contract" in groups and unit_id is not None:
        today = today or datetime.now(SCHEDULE_TZ).date()
        rows = list(
            await session.scalars(
                scoped(select(Contract).where(Contract.unit_id == unit_id), Contract).order_by(
                    Contract.start_date.desc(), Contract.id
                )
            )
        )
        own_parties: set[uuid.UUID] = set()
        if rows and contact_id is not None:
            own_parties = set(
                await session.scalars(
                    scoped(
                        select(PartyMember.party_id).where(
                            PartyMember.contact_id == contact_id,
                            PartyMember.party_id.in_([r.party_id for r in rows]),
                        ),
                        PartyMember,
                    )
                )
            )

        def rank(row: Contract) -> tuple[int, int, int, int, str]:
            status = contract_status(row.start_date, row.end_date, row.termination_date, today)
            return (
                0 if row.party_id in own_parties else 1,
                0 if status in ("active", "terminated") else 1,
                0 if str(normalise(row.kind)) == "tenancy" else 1,
                # Latest start first, then the id, so the choice is stable.
                -row.start_date.toordinal(),
                str(row.id),
            )

        if rows:
            best = min(rows, key=rank)
            data = _pick(best, RELATED_FIELDS["contract"])
            data["status"] = contract_status(
                best.start_date, best.end_date, best.termination_date, today
            )
            context["contract"] = data
    return context


def related_for_rules(rules: list[AutomationRule]) -> set[str]:
    """Union of the related groups the condition trees of ``rules`` read."""
    groups: set[str] = set()
    for rule in rules:
        groups |= related_groups(rule.conditions)
    return groups


# --- actions ------------------------------------------------------------------------------


def _uuid_or_none(value: Any, label: str) -> uuid.UUID | None:
    if value in (None, ""):
        return None
    try:
        return uuid.UUID(str(value))
    except ValueError as exc:
        raise ActionError(f"{label}: keine gültige UUID ({value!r}).") from exc


async def _users_with_role(
    session: AsyncSession, tenant_id: uuid.UUID, codes: list[str]
) -> list[uuid.UUID]:
    from mhvp.platform.models import Membership, MembershipRole, MembershipStatus, Role

    if not codes:
        return []
    rows = await session.execute(
        select(Membership.user_id)
        .join(MembershipRole, MembershipRole.membership_id == Membership.id)
        .join(Role, Role.id == MembershipRole.role_id)
        .where(
            Membership.tenant_id == tenant_id,
            Membership.status == MembershipStatus.ACTIVE,
            Role.tenant_id == tenant_id,
            Role.code.in_(codes),
        )
        .distinct()
    )
    return [row[0] for row in rows]


async def _assert_team(session: AsyncSession, team_id: uuid.UUID | None) -> None:
    if team_id is not None and await session.get(Team, team_id) is None:
        raise ActionError("Team nicht gefunden.")


async def _assert_member(
    session: AsyncSession, tenant_id: uuid.UUID, user_id: uuid.UUID | None
) -> None:
    from mhvp.platform.models import Membership, MembershipStatus

    if user_id is None:
        return
    found = await session.scalar(
        select(Membership.id).where(
            Membership.tenant_id == tenant_id,
            Membership.user_id == user_id,
            Membership.status == MembershipStatus.ACTIVE,
        )
    )
    if found is None:
        raise ActionError("Bearbeiter ist kein aktives Mitglied des Mandanten.")


async def _create_ticket(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event_id: uuid.UUID,
    action: CreateTicketAction,
    context: dict[str, Any],
    dry_run: bool,
) -> dict[str, Any]:
    from mhvp.tickets.routers import SLA_HOURS

    tpl = await session.get(TicketTemplate, action.template_id)
    if tpl is None:
        raise ActionError("Ticketvorlage nicht gefunden.")
    if not tpl.active:
        raise ActionError("Ticketvorlage ist deaktiviert.")
    values = {k: resolve_value(v, context) for k, v in action.fields.items()}
    title = render(action.title, context) or tpl.title
    priority_raw = values.pop("priority", None)
    priority = Priority(priority_raw) if priority_raw else tpl.default_priority
    team_id = _uuid_or_none(values.pop("team_id", tpl.default_team_id), "team_id")
    assignee = _uuid_or_none(
        values.pop("assignee_user_id", tpl.default_assignee_user_id), "assignee_user_id"
    )
    await _assert_team(session, team_id)
    await _assert_member(session, tenant_id, assignee)
    refs = {
        k: _uuid_or_none(values.pop(k, None), k) for k in ("property_id", "unit_id", "contact_id")
    }
    texts = {k: values.pop(k, None) for k in ("public_description", "internal_description")}
    category = values.pop("category", None) or tpl.category
    preview = {
        "type": "create_ticket",
        "template_id": str(tpl.id),
        "title": title,
        "priority": priority.value,
        "team_id": str(team_id) if team_id else None,
        "assignee_user_id": str(assignee) if assignee else None,
        "category": category,
        **{k: (str(v) if v else None) for k, v in refs.items()},
    }
    if dry_run:
        return preview | {"ok": True, "detail": "Testlauf: Ticket würde angelegt."}
    hours = tpl.sla_hours or SLA_HOURS[priority]
    ticket = Ticket(
        tenant_id=tenant_id,
        created_by=None,
        number=await next_number(session, tenant_id, "ticket"),
        template_id=tpl.id,
        category=category,
        topic=tpl.topic,
        title=title,
        public_description=texts["public_description"],
        internal_description=texts["internal_description"],
        priority=priority,
        team_id=team_id,
        assignee_user_id=assignee,
        source=TicketSource.MANUAL,
        checklist=[
            {
                "key": c["key"],
                "label": c["label"],
                "required": c.get("required", False),
                "done": False,
                "done_by": None,
                "done_at": None,
            }
            for c in tpl.checklist
        ],
        sla_due_at=datetime.now(UTC) + timedelta(hours=hours),
        **refs,
    )
    session.add(ticket)
    await session.flush()
    from mhvp.sla.service import start_clock

    await start_clock(session, tenant_id, ticket.id, ticket.priority)
    session.add(
        TicketEvent(
            tenant_id=tenant_id,
            ticket_id=ticket.id,
            kind="created",
            user_id=None,
            data={"routing": "automation", "rule_id": str(rule.id), "rule_name": rule.name},
        )
    )
    if assignee:
        await notify(
            session,
            tenant_id=tenant_id,
            user_id=assignee,
            kind="ticket_assigned",
            title=f"Ticket {ticket.number}: {ticket.title}",
            entity_type="ticket",
            entity_id=ticket.id,
        )
    await emit(
        session,
        tenant_id=tenant_id,
        type="ticket.created",
        entity_type="ticket",
        entity_id=ticket.id,
        actor_user_id=None,
        payload={"number": ticket.number, "source": ticket.source.value}
        | automation_marker(rule.id, event_id),
    )
    return preview | {
        "ok": True,
        "entity_type": "ticket",
        "entity_id": str(ticket.id),
        "detail": f"Ticket {ticket.number} angelegt.",
    }


async def _notify(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    action: NotifyAction,
    context: dict[str, Any],
    dry_run: bool,
) -> dict[str, Any]:
    recipients = set(action.user_ids)
    recipients.update(await _users_with_role(session, tenant_id, action.role_codes))
    title = render(action.title, context) or rule.name
    body = render(action.body, context)
    entity_id = _uuid_or_none(context.get("entity_id"), "entity_id")
    preview = {
        "type": "notify",
        "title": title,
        "body": body,
        "user_ids": sorted(str(u) for u in recipients),
    }
    if dry_run:
        return preview | {"ok": True, "detail": f"Testlauf: {len(recipients)} Empfänger."}
    created = 0
    for user_id in sorted(recipients, key=str):
        await _assert_member(session, tenant_id, user_id)
        row = await notify(
            session,
            tenant_id=tenant_id,
            user_id=user_id,
            kind=NOTIFICATION_KIND,
            title=title[:300],
            body=body,
            entity_type=context.get("entity_type"),
            entity_id=entity_id,
        )
        created += 1 if row is not None else 0
    return preview | {"ok": True, "detail": f"{created} Benachrichtigungen angelegt."}


async def _set_ticket_field(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event_id: uuid.UUID,
    action: SetTicketFieldAction,
    context: dict[str, Any],
    dry_run: bool,
) -> dict[str, Any]:
    message_event = context.get("entity_type") == "message"
    if context.get("entity_type") != "ticket" and not message_event:
        raise ActionError("Feld setzen braucht ein Ereignis zu einem Ticket.")
    if not context.get("entity_id") and not dry_run:
        raise ActionError("Feld setzen braucht ein Ereignis zu einem Ticket.")
    value = resolve_value(action.value, context)
    # A mail event (rule M9-11) sets the field on the ticket of the mail, if it has one.
    raw_ticket = (context.get("entity") or {}).get("ticket_id") if message_event else None
    if message_event:
        ticket_id = uuid.UUID(str(raw_ticket)) if raw_ticket else None
    else:
        ticket_id = uuid.UUID(str(context["entity_id"])) if context.get("entity_id") else None
    new_value: Any
    if action.field == "priority":
        new_value = Priority(str(value))
    elif action.field == "topic":
        new_value = None if value in (None, "") else str(value)[:32]
        if new_value is not None and not await _known_topic(session, tenant_id, new_value):
            raise ActionError(f"Unbekanntes Thema: {new_value}")
    elif action.field in ("team_id", "assignee_user_id"):
        new_value = _uuid_or_none(value, action.field)
        if action.field == "team_id":
            await _assert_team(session, new_value)
        else:
            await _assert_member(session, tenant_id, new_value)
    else:
        new_value = None if value in (None, "") else str(value)[:100]
    preview = {
        "type": "set_ticket_field",
        "field": action.field,
        "value": normalise(new_value),
        "entity_type": "ticket",
        "entity_id": str(ticket_id) if ticket_id else None,
    }
    if dry_run:
        return preview | {"ok": True, "detail": "Testlauf: Feld würde gesetzt."}
    if ticket_id is None:
        if message_event:
            return preview | {"ok": True, "detail": "Mail ohne Ticket; nichts gesetzt."}
        return preview | {"ok": True, "detail": "Testlauf: Feld würde gesetzt."}
    ticket = await session.get(Ticket, ticket_id)
    if ticket is None:
        raise ActionError("Ticket nicht gefunden.")
    if ticket.merged_into_ticket_id is not None:
        raise ActionError("Ticket ist zusammengeführt; keine Änderung.")
    old_value = normalise(getattr(ticket, action.field))
    if old_value == normalise(new_value):
        return preview | {"ok": True, "detail": "Wert bereits gesetzt."}
    setattr(ticket, action.field, new_value)
    ticket.updated_by = None
    session.add(
        TicketEvent(
            tenant_id=tenant_id,
            ticket_id=ticket.id,
            kind="automation",
            user_id=None,
            data={
                "rule_id": str(rule.id),
                "rule_name": rule.name,
                "field": action.field,
                "old": old_value,
                "new": normalise(new_value),
            },
        )
    )
    if action.field == "assignee_user_id" and new_value is not None:
        await notify(
            session,
            tenant_id=tenant_id,
            user_id=new_value,
            kind="ticket_assigned",
            title=f"Ticket {ticket.number}: {ticket.title}",
            entity_type="ticket",
            entity_id=ticket.id,
        )
    await emit(
        session,
        tenant_id=tenant_id,
        type="ticket.field_set",
        entity_type="ticket",
        entity_id=ticket.id,
        actor_user_id=None,
        payload={"field": action.field} | automation_marker(rule.id, event_id),
        changes={action.field: {"old": old_value, "new": normalise(new_value)}},
    )
    return preview | {"ok": True, "detail": f"{action.field} gesetzt."}


async def _known_topic(session: AsyncSession, tenant_id: uuid.UUID, code: str) -> bool:
    from mhvp.communication.assignment import _tenant_extra_catalogue
    from mhvp.tickets.competences import is_known_code

    return is_known_code(code, await _tenant_extra_catalogue(session, tenant_id))


async def _assign_record(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event_id: uuid.UUID,
    action: AssignRecordAction,
    context: dict[str, Any],
    dry_run: bool,
) -> dict[str, Any]:
    """Lern-Workflow (rule M9-11): assignment of a contact, property or unit to the mail of the
    event or to its ticket, through the assignment review (``apply_rule_assignment``)."""
    from mhvp.communication.assignment_review import apply_rule_assignment

    entity_type = context.get("entity_type")
    if entity_type not in ("message", "ticket"):
        raise ActionError("Zuordnen braucht ein Ereignis zu einer Mail oder einem Ticket.")
    target_id: uuid.UUID | None
    if action.target == entity_type:
        target_id = uuid.UUID(str(context["entity_id"])) if context.get("entity_id") else None
    elif action.target == "ticket" and entity_type == "message":
        raw = (context.get("entity") or {}).get("ticket_id")
        target_id = uuid.UUID(str(raw)) if raw else None
    else:
        raise ActionError("Zuordnen an eine Mail braucht ein Mailereignis.")
    preview = {
        "type": "assign_record",
        "dimension": action.dimension,
        "value": str(action.value),
        "entity_type": action.target,
        "entity_id": str(target_id) if target_id else None,
    }
    if dry_run:
        return preview | {"ok": True, "detail": "Testlauf: Zuordnung würde gesetzt."}
    if target_id is None:
        return preview | {"ok": True, "detail": "Kein Ticket zur Mail; nichts zugeordnet."}
    try:
        outcome = await apply_rule_assignment(
            session,
            entity_type=action.target,
            entity_id=target_id,
            dimension=action.dimension,
            value=action.value,
            rule_id=rule.id,
            rule_name=rule.name,
            marker=automation_marker(rule.id, event_id),
        )
    except LookupError as exc:
        raise ActionError(str(exc)) from exc
    return preview | {"ok": True, "detail": outcome}


TASK_CATEGORY = "task"


async def _create_task(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event_id: uuid.UUID,
    action: CreateTaskAction,
    context: dict[str, Any],
    dry_run: bool,
) -> dict[str, Any]:
    """M9-08: a lightweight internal task, without a ticket template. Never a WEG resolution,
    payment or approval (rule 0.1.6); it is a follow-up ticket in category ``task``."""
    title = render(action.title, context) or action.title
    description = render(action.description, context)
    assignee = action.assignee_user_id
    await _assert_member(session, tenant_id, assignee)
    preview = {
        "type": "create_task",
        "title": title,
        "assignee_user_id": str(assignee) if assignee else None,
        "due_in_days": action.due_in_days,
    }
    if dry_run:
        return preview | {"ok": True, "detail": "Testlauf: Aufgabe würde angelegt."}
    priority = Priority(action.priority) if action.priority else Priority.NORMAL
    from mhvp.tickets.routers import SLA_HOURS

    hours = SLA_HOURS[priority]
    sla_due_at = datetime.now(UTC) + timedelta(hours=hours)
    if action.due_in_days is not None:
        sla_due_at = datetime.now(UTC) + timedelta(days=action.due_in_days)
    ticket = Ticket(
        tenant_id=tenant_id,
        created_by=None,
        number=await next_number(session, tenant_id, "ticket"),
        category=TASK_CATEGORY,
        title=title,
        internal_description=description,
        priority=priority,
        assignee_user_id=assignee,
        source=TicketSource.MANUAL,
        sla_due_at=sla_due_at,
    )
    session.add(ticket)
    await session.flush()
    from mhvp.sla.service import start_clock

    await start_clock(session, tenant_id, ticket.id, ticket.priority)
    session.add(
        TicketEvent(
            tenant_id=tenant_id,
            ticket_id=ticket.id,
            kind="created",
            user_id=None,
            data={"routing": "automation", "rule_id": str(rule.id), "rule_name": rule.name},
        )
    )
    if assignee:
        await notify(
            session,
            tenant_id=tenant_id,
            user_id=assignee,
            kind="ticket_assigned",
            title=f"Aufgabe {ticket.number}: {ticket.title}",
            entity_type="ticket",
            entity_id=ticket.id,
        )
    await emit(
        session,
        tenant_id=tenant_id,
        type="ticket.created",
        entity_type="ticket",
        entity_id=ticket.id,
        actor_user_id=None,
        payload={"number": ticket.number, "source": ticket.source.value}
        | automation_marker(rule.id, event_id),
    )
    return preview | {
        "ok": True,
        "entity_type": "ticket",
        "entity_id": str(ticket.id),
        "detail": f"Aufgabe {ticket.number} angelegt.",
    }


# --- stage 2 actions (A39) ---------------------------------------------------------------


def seal_actions(actions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Encrypt a freshly given webhook secret (tenant scope of the open transaction) and drop
    the plaintext; actions without a new secret keep their stored ``secret_enc``."""
    sealed: list[dict[str, Any]] = []
    for action in actions:
        secret = action.get("secret") if action.get("type") == "webhook" else None
        if secret:
            action = {k: v for k, v in action.items() if k != "secret"}
            action["secret_enc"] = base64.b64encode(crypto.encrypt(str(secret))).decode()
        sealed.append(action)
    return sealed


def carry_secrets(new: list[dict[str, Any]], old: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """On a patch without a new secret, keep the stored secret of the webhook with the same
    position and URL (the API never returns ``secret_enc``, so the client cannot send it)."""
    out: list[dict[str, Any]] = []
    for index, action in enumerate(new):
        if (
            action.get("type") == "webhook"
            and not action.get("secret")
            and not action.get("secret_enc")
            and index < len(old)
            and old[index].get("type") == "webhook"
            and old[index].get("url") == action.get("url")
            and old[index].get("secret_enc")
        ):
            action = action | {"secret_enc": old[index]["secret_enc"]}
        out.append(action)
    return out


def public_actions(actions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Actions as returned by the API: the webhook secret is replaced by ``has_secret``."""
    out: list[dict[str, Any]] = []
    for action in actions:
        if action.get("type") == "webhook":
            action = {k: v for k, v in action.items() if k not in ("secret", "secret_enc")}
            action["has_secret"] = True
        out.append(action)
    return out


def webhook_body(rule: AutomationRule, context: dict[str, Any], extra: dict[str, str]) -> bytes:
    document = {
        "rule": {"id": str(rule.id), "name": rule.name},
        "tenant_id": str(rule.tenant_id),
        "event": {
            "type": context.get("type"),
            "entity_type": context.get("entity_type"),
            "entity_id": context.get("entity_id"),
            "payload": context.get("payload"),
        },
        "entity": context.get("entity"),
        "sent_at": datetime.now(UTC).isoformat(),
        **{k: render(v, context) for k, v in extra.items()},
    }
    return json.dumps(document, sort_keys=True, separators=(",", ":"), default=str).encode()


async def _webhook(
    *,
    rule: AutomationRule,
    action: WebhookAction,
    action_index: int,
    context: dict[str, Any],
    dry_run: bool,
    settings: Settings,
) -> dict[str, Any]:
    """Check the target and the secret, then hand the payload to the outbox (A82): the run
    does not call the target itself; ``deliver_due_webhooks`` sends it after the run has been
    recorded and retries after the schedule of ``mhvp.core.webhooks``. Target and secret
    errors are configuration errors of the rule and fail the run without retry."""
    from mhvp.core.webhooks import UnsafeWebhookTargetError, check_target, pin_target

    preview = {"type": "webhook", "url": action.url}
    allow_private = settings.webhook_allow_private_targets
    try:
        if dry_run:
            # Review 1.22 Nr. 13: the dry run checks the URL only, without a DNS query for a
            # freely chosen host name; the resolution happens on the real call.
            check_target(action.url, allow_private=allow_private, resolve=False)
            return preview | {"ok": True, "detail": "Testlauf: Webhook würde gesendet."}
        # The target is resolved once here so that a rule with an unsafe target fails its
        # run; the delivery pins the checked address again on every attempt (Review 1.22 Nr. 12).
        pin_target(action.url, allow_private=allow_private)
    except UnsafeWebhookTargetError as exc:
        raise ActionError(f"Webhook-Ziel nicht zulässig: {exc}.") from exc
    if not action.secret_enc:
        raise ActionError("Webhook ohne gespeichertes Geheimnis.")
    try:
        crypto.decrypt(base64.b64decode(action.secret_enc))
    except (crypto.CryptoError, ValueError) as exc:
        raise ActionError("Webhook-Geheimnis kann nicht gelesen werden.") from exc
    body = webhook_body(rule, context, action.extra)
    return preview | {
        "ok": True,
        "detail": "Webhook eingereiht.",
        PENDING_DELIVERY_KEY: {
            "action_index": action_index,
            "url": action.url,
            "event_type": str(context.get("type") or ""),
            "body": body.decode(),
        },
    }


# --- webhook outbox (A82) -----------------------------------------------------------------


def schedule_after_attempt(delivery: AutomationWebhookDelivery, *, ok: bool, now: datetime) -> None:
    """State transition after one attempt (``attempts`` already incremented): succeeded, the
    next slot of ``WEBHOOK_RETRY_SCHEDULE_SECONDS`` (1, 5, 15, 60 minutes) counted from
    ``now``, or ``dead`` once ``WEBHOOK_MAX_ATTEMPTS`` (5) is reached (M9-08). The caller
    (``deliver_due_webhooks``) notifies the rule owner exactly once a row goes dead."""
    if ok:
        delivery.status = DELIVERY_SUCCEEDED
        delivery.delivered_at = now
        delivery.next_attempt_at = None
    elif delivery.attempts >= WEBHOOK_MAX_ATTEMPTS:
        delivery.status = DELIVERY_DEAD
        delivery.next_attempt_at = None
    else:
        delivery.status = DELIVERY_PENDING
        delivery.next_attempt_at = now + timedelta(
            seconds=WEBHOOK_RETRY_SCHEDULE_SECONDS[delivery.attempts - 1]
        )


def _stored_webhook_secret(rule: AutomationRule | None, action_index: int, url: str) -> str:
    """Secret of the webhook action at ``action_index`` of the rule as stored now; the rule
    may have changed since the run, so the URL must still match."""
    if rule is None or action_index >= len(rule.actions):
        raise ActionError("Regel oder Aktion nicht mehr vorhanden.")
    stored = rule.actions[action_index]
    if stored.get("type") != "webhook" or stored.get("url") != url:
        raise ActionError("Webhook-Aktion der Regel wurde geändert.")
    if not stored.get("secret_enc"):
        raise ActionError("Webhook ohne gespeichertes Geheimnis.")
    try:
        return crypto.decrypt(base64.b64decode(stored["secret_enc"]))
    except (crypto.CryptoError, ValueError) as exc:
        raise ActionError("Webhook-Geheimnis kann nicht gelesen werden.") from exc


async def attempt_webhook_delivery(
    session: AsyncSession,
    delivery: AutomationWebhookDelivery,
    *,
    client: httpx.AsyncClient,
    settings: Settings,
    now: datetime,
) -> bool:
    """One signed attempt of a pending delivery; updates the row like the core webhooks do.
    Every attempt of this delivery carries the same ``Idempotency-Key`` (set once when the
    row was created, M9-08), so a receiver that saw an earlier attempt can recognise a retry
    even when the response of that earlier attempt was lost."""
    from mhvp.core.webhooks import SIGNATURE_HEADER, UnsafeWebhookTargetError, pin_target, sign

    delivery.attempts += 1
    ok = False
    started = time.monotonic()
    try:
        rule = await session.get(AutomationRule, delivery.rule_id)
        secret = _stored_webhook_secret(rule, delivery.action_index, delivery.url)
        target = pin_target(delivery.url, allow_private=settings.webhook_allow_private_targets)
        body = delivery.body.encode()
        headers = {
            "Content-Type": "application/json",
            "X-MHVP-Event": delivery.event_type,
            "X-MHVP-Rule": str(delivery.rule_id),
            "X-MHVP-Delivery": str(delivery.id),
            "Idempotency-Key": delivery.idempotency_key or str(delivery.id),
            SIGNATURE_HEADER: sign(secret, body, int(time.time())),
        }
        response = await client.post(
            target.url,
            content=body,
            headers=headers | target.headers,
            extensions=target.extensions,
            follow_redirects=False,
        )
        delivery.last_status_code = response.status_code
        ok = 200 <= response.status_code < 300
        delivery.last_error = None if ok else f"HTTP {response.status_code}"
    except (ActionError, UnsafeWebhookTargetError) as exc:
        delivery.last_error = str(exc)[:200]
    except httpx.HTTPError as exc:
        delivery.last_error = type(exc).__name__[:200]
    delivery.last_duration_ms = int((time.monotonic() - started) * 1000)
    schedule_after_attempt(delivery, ok=ok, now=now)
    return ok


async def deliver_due_webhooks(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    *,
    now: datetime,
    settings: Settings,
    limit: int = 100,
) -> dict[str, int]:
    """Send every pending delivery of the tenant that is due; rows are locked with
    ``SKIP LOCKED`` so that two workers never send the same delivery twice."""
    due = list(
        await session.scalars(
            select(AutomationWebhookDelivery)
            .where(
                AutomationWebhookDelivery.tenant_id == tenant_id,
                AutomationWebhookDelivery.status == DELIVERY_PENDING,
                AutomationWebhookDelivery.next_attempt_at <= now,
            )
            .order_by(AutomationWebhookDelivery.next_attempt_at, AutomationWebhookDelivery.id)
            .limit(limit)
            .with_for_update(skip_locked=True)
        )
    )
    totals = {"webhooks": 0, "webhooks_failed": 0}
    if not due:
        return totals
    async with httpx.AsyncClient(timeout=WEBHOOK_TIMEOUT_SECONDS) as client:
        for delivery in due:
            totals["webhooks"] += 1
            if not await attempt_webhook_delivery(
                session, delivery, client=client, settings=settings, now=now
            ):
                totals["webhooks_failed"] += 1
                if delivery.status == DELIVERY_DEAD and not delivery.owner_notified:
                    await _notify_owner_dead(session, delivery)
                    delivery.owner_notified = True
    await session.flush()
    return totals


async def _notify_owner_dead(session: AsyncSession, delivery: AutomationWebhookDelivery) -> None:
    """M9-08: after ``WEBHOOK_MAX_ATTEMPTS`` failed attempts, tell the rule owner that the
    delivery is dead and needs a manual look or resend. Prefers the explicit
    ``owner_user_id`` (Kleinbefund 27.09.2026); falls back to whoever last saved the rule, or
    who created it, when no owner is set."""
    rule = await session.get(AutomationRule, delivery.rule_id)
    if rule is None:
        return
    owner_id = rule.owner_user_id or rule.updated_by or rule.created_by
    if owner_id is None:
        return
    await notify(
        session,
        tenant_id=delivery.tenant_id,
        user_id=owner_id,
        kind="automation_webhook_dead",
        title=f"Regel-Webhook fehlgeschlagen: {rule.name}",
        body=f"Zustellung an {delivery.url} nach {delivery.attempts} Versuchen aufgegeben "
        f"(letzter Fehler: {delivery.last_error or delivery.last_status_code}).",
        entity_type="automation_rule",
        entity_id=rule.id,
    )


def redeliver_webhook(delivery: AutomationWebhookDelivery, *, now: datetime | None = None) -> None:
    """Manual redelivery from the API (M9-08): back to pending, due now. A ``dead`` row gets a
    fresh attempt budget (the operator has looked at it), a still-``pending`` or ``succeeded``
    row keeps its attempt count so the log stays honest about how often it was tried."""
    if delivery.status == DELIVERY_DEAD:
        delivery.attempts = 0
        delivery.owner_notified = False
    delivery.status = DELIVERY_PENDING
    delivery.next_attempt_at = now or datetime.now(UTC)


def delivery_out(delivery: AutomationWebhookDelivery) -> dict[str, Any]:
    return {
        "id": delivery.id,
        "run_id": delivery.run_id,
        "action_index": delivery.action_index,
        "url": delivery.url,
        "status": delivery.status,
        "attempts": delivery.attempts,
        "max_attempts": WEBHOOK_MAX_ATTEMPTS,
        "next_attempt_at": delivery.next_attempt_at,
        "last_status_code": delivery.last_status_code,
        "last_error": delivery.last_error,
        "last_duration_ms": delivery.last_duration_ms,
        "idempotency_key": delivery.idempotency_key,
        "delivered_at": delivery.delivered_at,
    }


async def _ticket_of(context: dict[str, Any], session: AsyncSession, what: str) -> Ticket:
    if context.get("entity_type") != "ticket" or not context.get("entity_id"):
        raise ActionError(f"{what} braucht ein Ereignis zu einem Ticket.")
    ticket = await session.get(Ticket, uuid.UUID(str(context["entity_id"])))
    if ticket is None:
        raise ActionError("Ticket nicht gefunden.")
    return ticket


async def _mail_draft(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    action: MailDraftAction,
    context: dict[str, Any],
    dry_run: bool,
) -> dict[str, Any]:
    from mhvp.communication.models import Message
    from mhvp.tickets import reply_templates
    from mhvp.tickets.models import TicketReplyTemplate
    from mhvp.tickets.routers import _reply_context

    tpl = await session.get(TicketReplyTemplate, action.reply_template_id)
    if tpl is None:
        raise ActionError("Antwortvorlage nicht gefunden.")
    preview: dict[str, Any] = {"type": "mail_draft", "template_name": tpl.name}
    if dry_run and not context.get("entity_id"):
        return preview | {"ok": True, "detail": "Testlauf: E-Mail-Entwurf würde angelegt."}
    ticket = await _ticket_of(context, session, "E-Mail-Entwurf")
    ctx = await _reply_context(session, ticket)
    if not ctx["to_addresses"]:
        raise ActionError("Kein Empfänger: das Ticket hat keinen Kontakt mit E-Mail-Adresse.")
    subject = reply_templates.render(tpl.subject, ctx["values"])[:998]
    body = reply_templates.render(tpl.body, ctx["values"])
    preview |= {"subject": subject, "to_addresses": ctx["to_addresses"]}
    if dry_run:
        return preview | {"ok": True, "detail": "Testlauf: E-Mail-Entwurf würde angelegt."}
    inbound = ctx["inbound"]
    mailbox = ctx["mailbox"]
    draft = Message(
        tenant_id=tenant_id,
        created_by=None,
        direction="out",
        status="draft",
        mailbox_id=mailbox.id if mailbox else None,
        to_addresses=ctx["to_addresses"],
        subject=subject,
        body=body,
        in_reply_to=inbound.header_message_id if inbound else None,
        thread_id=(inbound.thread_id or inbound.id) if inbound else None,
        contact_id=ctx["contact"].id if ctx["contact"] else None,
        property_id=ticket.property_id,
        ticket_id=ticket.id,
        attachment_document_ids=list(tpl.attachment_document_ids),
    )
    session.add(draft)
    await session.flush()
    session.add(
        TicketEvent(
            tenant_id=tenant_id,
            ticket_id=ticket.id,
            kind="automation",
            user_id=None,
            data={
                "rule_id": str(rule.id),
                "rule_name": rule.name,
                "action": "mail_draft",
                "message_id": str(draft.id),
                "template_id": str(tpl.id),
            },
        )
    )
    return preview | {
        "ok": True,
        "entity_type": "message",
        "entity_id": str(draft.id),
        "detail": "E-Mail-Entwurf angelegt (Freigabe und Versand bleiben manuell).",
    }


async def _letter_draft(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event_id: uuid.UUID,
    action: LetterDraftAction,
    context: dict[str, Any],
    dry_run: bool,
    settings: Settings,
) -> dict[str, Any]:
    import html

    from mhvp.core.problems import ProblemError
    from mhvp.documents import letters
    from mhvp.documents import services as docs
    from mhvp.documents.blobs import BlobStore
    from mhvp.documents.models import DocumentSource, DocumentTemplate, LinkRole

    tpl = await session.get(DocumentTemplate, action.template_id)
    if tpl is None or not tpl.active:
        raise ActionError("Briefvorlage nicht gefunden oder nicht aktiv.")
    ticket: Ticket | None = None
    if context.get("entity_type") == "ticket" and context.get("entity_id"):
        ticket = await session.get(Ticket, uuid.UUID(str(context["entity_id"])))
    contact_id = action.contact_id or (
        (ticket.contact_id or ticket.initiator_contact_id) if ticket else None
    )
    preview: dict[str, Any] = {"type": "letter_draft", "template_code": tpl.code}
    if contact_id is None:
        if dry_run and context.get("entity_type") == "ticket" and not context.get("entity_id"):
            return preview | {"ok": True, "detail": "Testlauf: Brief würde als Dokument abgelegt."}
        raise ActionError("Kein Empfänger: weder fester Kontakt noch Kontakt am Ticket.")
    blobs = BlobStore(settings)
    try:
        head = await docs.letterhead(session, blobs)
        contact, lines, recipient = await docs.recipient(session, contact_id)
        letter_context, info, links = await docs.entity_context(
            session,
            ticket.property_id if ticket else None,
            ticket.unit_id if ticket else None,
            None,
        )
    except ProblemError as exc:
        raise ActionError(exc.detail or exc.error.title) from exc
    letter_date = datetime.now(UTC).astimezone().date()
    letter_context.update(
        empfaenger=recipient,
        felder={k: render(v, context) or "" for k, v in action.fields.items()},
        datum=letter_date.strftime("%d.%m.%Y"),
        gesellschaft={"name": head.company.get("name", "")},
    )
    try:
        subject = letters.render_text(tpl.subject, letter_context)
        body = letters.render_text(tpl.body, letter_context)
    except letters.PlaceholderError as exc:
        raise ActionError(f"Platzhalter: {exc}") from exc
    preview |= {"subject": html.unescape(subject), "contact_id": str(contact.id)}
    if dry_run:
        return preview | {"ok": True, "detail": "Testlauf: Brief würde als Dokument abgelegt."}
    reference = render(action.reference, context)
    if reference:
        info.insert(0, ("Unser Zeichen", reference))
    # A83: an automatically generated letter is visibly a draft (notice on the PDF), lands in
    # the category "Entwurf" and carries the rule in its metadata; it is never sent.
    draft_notice = DRAFT_NOTICE.format(date=letter_date.strftime("%d.%m.%Y"), rule=rule.name)
    pdf = letters.render_pdf(
        head,
        letters.Letter(
            lines,
            subject,
            body,
            letter_date,
            info,
            signatory=action.signatory,
            draft_notice=draft_notice,
        ),
    )
    document = await docs.store_document(
        session,
        blobs,
        tenant_id=tenant_id,
        data=pdf,
        title=html.unescape(subject),
        filename=f"{letter_date.isoformat()}_{tpl.code}_{contact.display_name}.pdf"[:255],
        mime_type="application/pdf",
        source=DocumentSource.GENERATED,
        category_id=await _draft_category_id(session, tenant_id),
        links=[("contact", contact.id, LinkRole.GENERATED)]
        + [(t, i, LinkRole.GENERATED) for t, i in links]
        + ([("ticket", ticket.id, LinkRole.GENERATED)] if ticket else []),
        created_by=None,
    )
    document.source_meta = {
        "is_draft": True,
        "automation_rule_id": str(rule.id),
        "automation_rule_name": rule.name,
        "automation_event_id": str(event_id),
        "generated_at": datetime.now(UTC).isoformat(),
        "template_code": tpl.code,
        "template_category_id": str(tpl.category_id) if tpl.category_id else None,
        "draft_notice": draft_notice,
    }
    if ticket is not None:
        session.add(
            TicketEvent(
                tenant_id=tenant_id,
                ticket_id=ticket.id,
                kind="automation",
                user_id=None,
                data={
                    "rule_id": str(rule.id),
                    "rule_name": rule.name,
                    "action": "letter_draft",
                    "document_id": str(document.id),
                },
            )
        )
    await emit(
        session,
        tenant_id=tenant_id,
        type="document.generated",
        entity_type="document",
        entity_id=document.id,
        actor_user_id=None,
        payload={"template": tpl.code, "template_version": tpl.version}
        | automation_marker(rule.id, event_id),
    )
    return preview | {
        "ok": True,
        "entity_type": "document",
        "entity_id": str(document.id),
        "detail": "Brief als Dokument abgelegt (nicht versendet).",
    }


async def _draft_category_id(session: AsyncSession, tenant_id: uuid.UUID) -> uuid.UUID:
    """Category "Entwurf" of the tenant (code ``entwurf``), created on first use (A83)."""
    from mhvp.documents.models import DocumentCategory

    existing = await session.scalar(
        select(DocumentCategory.id).where(
            DocumentCategory.tenant_id == tenant_id, DocumentCategory.code == DRAFT_CATEGORY_CODE
        )
    )
    if existing is not None:
        return existing
    category = DocumentCategory(
        tenant_id=tenant_id, code=DRAFT_CATEGORY_CODE, name=DRAFT_CATEGORY_NAME, sort_order=999
    )
    session.add(category)
    await session.flush()
    return category.id


async def _ai_task(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    action: AiTaskAction,
    context: dict[str, Any],
    dry_run: bool,
    settings: Settings,
) -> dict[str, Any]:
    from mhvp.ai.models import AiTask
    from mhvp.ai.routers import create_extraction_run

    instruction = render(action.instruction, context) or action.instruction
    preview = {"type": "ai_task", "task": action.task, "instruction": instruction[:200]}
    if dry_run:
        return preview | {"ok": True, "detail": "Testlauf: KI-Aufgabe würde gestartet."}
    entity_id = _uuid_or_none(context.get("entity_id"), "entity_id")
    run_id = await create_extraction_run(
        session,
        tenant_id,
        None,
        AiTask(action.task),
        [],
        instruction,
        str(context.get("entity_type") or "automation"),
        entity_id,
        trigger=f"automation:{rule.id}",
    )
    queued = False
    if not settings.ai_inline:
        try:
            from mhvp.worker import get_celery

            get_celery().send_task(
                "mhvp.ai.run", args=[str(tenant_id), str(run_id), None], queue="io"
            )
            queued = True
        except Exception:
            log.warning("could not queue automation ai task", extra={"run_id": str(run_id)})
    return preview | {
        "ok": True,
        "entity_type": "ai_task_run",
        "entity_id": str(run_id),
        "queued": queued,
        "detail": "KI-Aufgabe angelegt (nur Vorschlag).",
    }


async def execute_actions(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event_id: uuid.UUID,
    context: dict[str, Any],
    dry_run: bool,
    settings: Settings | None = None,
) -> list[dict[str, Any]]:
    """Run the rule's actions in order. Raises ``ActionError`` on the first failing action
    (the caller rolls back the savepoint and records the failure)."""
    settings = settings or get_settings()
    results: list[dict[str, Any]] = []
    for index, action in enumerate(parse_actions(rule.actions, stored=True)):
        results.append(
            await _execute_one(
                session,
                tenant_id=tenant_id,
                rule=rule,
                event_id=event_id,
                action=action,
                action_index=index,
                context=context,
                dry_run=dry_run,
                settings=settings,
            )
        )
    return results


async def _execute_one(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event_id: uuid.UUID,
    action: Action,
    action_index: int,
    context: dict[str, Any],
    dry_run: bool,
    settings: Settings,
) -> dict[str, Any]:
    if isinstance(action, CreateTicketAction):
        return await _create_ticket(
            session,
            tenant_id=tenant_id,
            rule=rule,
            event_id=event_id,
            action=action,
            context=context,
            dry_run=dry_run,
        )
    if isinstance(action, NotifyAction):
        return await _notify(
            session, tenant_id=tenant_id, rule=rule, action=action, context=context, dry_run=dry_run
        )
    if isinstance(action, WebhookAction):
        return await _webhook(
            rule=rule,
            action=action,
            action_index=action_index,
            context=context,
            dry_run=dry_run,
            settings=settings,
        )
    if isinstance(action, MailDraftAction):
        return await _mail_draft(
            session, tenant_id=tenant_id, rule=rule, action=action, context=context, dry_run=dry_run
        )
    if isinstance(action, LetterDraftAction):
        return await _letter_draft(
            session,
            tenant_id=tenant_id,
            rule=rule,
            event_id=event_id,
            action=action,
            context=context,
            dry_run=dry_run,
            settings=settings,
        )
    if isinstance(action, AiTaskAction):
        return await _ai_task(
            session,
            tenant_id=tenant_id,
            rule=rule,
            action=action,
            context=context,
            dry_run=dry_run,
            settings=settings,
        )
    if isinstance(action, AssignRecordAction):
        return await _assign_record(
            session,
            tenant_id=tenant_id,
            rule=rule,
            event_id=event_id,
            action=action,
            context=context,
            dry_run=dry_run,
        )
    if isinstance(action, CreateTaskAction):
        return await _create_task(
            session,
            tenant_id=tenant_id,
            rule=rule,
            event_id=event_id,
            action=action,
            context=context,
            dry_run=dry_run,
        )
    return await _set_ticket_field(
        session,
        tenant_id=tenant_id,
        rule=rule,
        event_id=event_id,
        action=action,
        context=context,
        dry_run=dry_run,
    )


# --- dry run ------------------------------------------------------------------------------


async def dry_run(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    context: dict[str, Any],
    settings: Settings | None = None,
) -> dict[str, Any]:
    """Evaluate a rule against a sample context without any effect (no run is recorded)."""
    if rule.trigger_kind == TRIGGER_SCHEDULE:
        trigger_matches = context.get("type") == SCHEDULE_EVENT_TYPE
    else:
        trigger_matches = context.get("type") == rule.trigger_event_type
    matched = trigger_matches and evaluate(rule.conditions, context)
    actions: list[dict[str, Any]] = []
    error: str | None = None
    if matched:
        try:
            # dry_run=True: every action returns its preview before any write.
            actions = await execute_actions(
                session,
                tenant_id=tenant_id,
                rule=rule,
                event_id=uuid.uuid4(),
                context=context,
                dry_run=True,
                settings=settings,
            )
        except ActionError as exc:
            error = str(exc)
    return {
        "status": RUN_STATUS_DRY_RUN,
        "trigger_matches": trigger_matches,
        "matched": bool(matched),
        "actions": actions,
        "error": error,
        "context": context,
    }


# --- schedules (A39) ----------------------------------------------------------------------


def schedule_context(rule: AutomationRule, due: datetime) -> dict[str, Any]:
    return {
        "type": SCHEDULE_EVENT_TYPE,
        "entity_type": "schedule",
        "entity_id": None,
        "actor_user_id": None,
        "payload": {
            "due_at": due.astimezone(UTC).isoformat(),
            "frequency": (rule.schedule or {}).get("frequency"),
            "rule_name": rule.name,
        },
        "entity": {},
    }


async def process_schedules(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    *,
    now: datetime,
    settings: Settings | None = None,
) -> dict[str, int]:
    """Run every active schedule rule whose latest due moment is newer than its watermark.
    The first pass of a rule only positions the watermark (moments before activation are
    history); the run id is derived from rule and due moment, so a concurrent worker cannot
    run the same window twice."""
    totals = {"runs": 0, "failed": 0}
    rules = list(
        await session.scalars(
            select(AutomationRule)
            .where(
                AutomationRule.tenant_id == tenant_id,
                AutomationRule.active.is_(True),
                AutomationRule.trigger_kind == TRIGGER_SCHEDULE,
            )
            .order_by(AutomationRule.created_at, AutomationRule.id)
        )
    )
    for rule in rules:
        if not rule.schedule:
            continue
        if rule.last_scheduled_at is None:
            rule.last_scheduled_at = now
            continue
        due = previous_due(rule.schedule, now)
        if due <= rule.last_scheduled_at:
            continue
        event = DomainEvent(
            id=window_event_id(rule.id, due),
            tenant_id=tenant_id,
            type=SCHEDULE_EVENT_TYPE,
            entity_type="schedule",
            entity_id=None,
            actor_user_id=None,
            occurred_at=due,
            payload={},
        )
        run = await _run_rule(
            session,
            tenant_id=tenant_id,
            rule=rule,
            event=event,
            context=schedule_context(rule, due),
            settings=settings,
            now=now,
        )
        rule.last_scheduled_at = due
        if run is None:
            continue
        totals["runs"] += 1
        if run.status == RUN_STATUS_FAILED:
            totals["failed"] += 1
    return totals


# --- processing ---------------------------------------------------------------------------


async def _run_rule(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event: DomainEvent,
    context: dict[str, Any] | None = None,
    settings: Settings | None = None,
    now: datetime | None = None,
) -> AutomationRun | None:
    """Execute one rule for one event, idempotent. ``None`` when already run or no match.
    ``event`` may be a transient schedule window (not persisted, see ``process_schedules``)."""
    existing = await session.scalar(
        select(AutomationRun.id).where(
            AutomationRun.rule_id == rule.id, AutomationRun.event_id == event.id
        )
    )
    if existing is not None:
        return None
    if context is None:
        context = await context_for_event(session, event)
    try:
        if not evaluate(rule.conditions, context):
            return None
    except Exception as exc:  # invalid stored tree: record and continue
        return await _record(session, tenant_id, rule, event, RUN_STATUS_FAILED, [], str(exc))
    try:
        async with session.begin_nested():
            actions = await execute_actions(
                session,
                tenant_id=tenant_id,
                rule=rule,
                event_id=event.id,
                context=context,
                dry_run=False,
                settings=settings,
            )
            run = await _record(
                session, tenant_id, rule, event, RUN_STATUS_EXECUTED, actions, None, now=now
            )
        return run
    except IntegrityError:
        # Concurrent worker already recorded this rule and event (unique constraint).
        return None
    except Exception as exc:
        log.warning(
            "automation rule failed",
            extra={"tenant_id": str(tenant_id), "rule_id": str(rule.id), "event_id": str(event.id)},
        )
        return await _record(
            session, tenant_id, rule, event, RUN_STATUS_FAILED, [], str(exc)[:2000]
        )


async def _record(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    rule: AutomationRule,
    event: DomainEvent,
    status: str,
    actions: list[dict[str, Any]],
    error: str | None,
    now: datetime | None = None,
) -> AutomationRun:
    """Write the run; webhook actions hand their payload to the outbox (A82), due at ``now``
    (the beat moment, so that the delivery step of the same pass sends it)."""
    now = now or datetime.now(UTC)
    pending = [(a.pop(PENDING_DELIVERY_KEY), a) for a in actions if PENDING_DELIVERY_KEY in a]
    run = AutomationRun(
        tenant_id=tenant_id,
        rule_id=rule.id,
        event_id=event.id,
        event_type=event.type,
        status=status,
        error=error,
        # Copy: the delivery ids are added below, and the JSONB column only writes a changed
        # value when the new list differs from the one inserted here.
        actions=[dict(a) for a in actions],
        finished_at=now,
    )
    session.add(run)
    await session.flush()
    for spec, result in pending:
        delivery = AutomationWebhookDelivery(
            tenant_id=tenant_id, run_id=run.id, rule_id=rule.id, next_attempt_at=now, **spec
        )
        session.add(delivery)
        await session.flush()
        # Stable across every retry of this row (M9-08); the id already is, this makes the
        # intent explicit for receivers keying on ``Idempotency-Key`` instead.
        delivery.idempotency_key = str(delivery.id)
        result["delivery_id"] = str(delivery.id)
    if pending:
        run.actions = [dict(a) for a in actions]
        await session.flush()
    return run


async def process_tenant(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    *,
    now: datetime | None = None,
    settings: Settings | None = None,
) -> dict[str, int]:
    """Process new events of one tenant since its watermark (see module docstring), then
    send the due webhook deliveries of the tenant (A82)."""
    now = now or datetime.now(UTC)
    settings = settings or get_settings()
    totals = {"events": 0, "runs": 0, "failed": 0, "webhooks": 0, "webhooks_failed": 0}
    scheduled = await process_schedules(session, tenant_id, now=now, settings=settings)
    totals["runs"] += scheduled["runs"]
    totals["failed"] += scheduled["failed"]
    await _process_events(session, tenant_id, now=now, settings=settings, totals=totals)
    delivered = await deliver_due_webhooks(session, tenant_id, now=now, settings=settings)
    totals["webhooks"] += delivered["webhooks"]
    totals["webhooks_failed"] += delivered["webhooks_failed"]
    return totals


async def _process_events(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    *,
    now: datetime,
    settings: Settings,
    totals: dict[str, int],
) -> None:
    cutoff = now - PROCESS_LAG
    watermark = await session.scalar(
        select(AutomationWatermark).where(AutomationWatermark.tenant_id == tenant_id)
    )
    if watermark is None:
        # First run: start at the current cut-off; older events are history, not triggers.
        watermark = AutomationWatermark(
            tenant_id=tenant_id, last_occurred_at=cutoff, last_event_id=None
        )
        session.add(watermark)
        await session.flush()
        return
    rules = list(
        await session.scalars(
            select(AutomationRule)
            .where(
                AutomationRule.tenant_id == tenant_id,
                AutomationRule.active.is_(True),
                AutomationRule.trigger_kind != TRIGGER_SCHEDULE,
            )
            .order_by(AutomationRule.created_at, AutomationRule.id)
        )
    )
    by_type: dict[str, list[AutomationRule]] = {}
    for rule in rules:
        if rule.trigger_event_type:
            by_type.setdefault(rule.trigger_event_type, []).append(rule)
    query = (
        select(DomainEvent)
        .where(DomainEvent.tenant_id == tenant_id, DomainEvent.occurred_at <= cutoff)
        .order_by(DomainEvent.occurred_at, DomainEvent.id)
        .limit(BATCH_LIMIT)
    )
    if watermark.last_occurred_at is not None:
        last_at, last_id = watermark.last_occurred_at, watermark.last_event_id
        if last_id is None:
            query = query.where(DomainEvent.occurred_at > last_at)
        else:
            query = query.where(
                (DomainEvent.occurred_at > last_at)
                | ((DomainEvent.occurred_at == last_at) & (DomainEvent.id > last_id))
            )
    events = list(await session.scalars(query))
    for event in events:
        totals["events"] += 1
        if is_automation_event(event.payload):
            continue
        matching = by_type.get(event.type, [])
        if not matching:
            continue
        # One context per event: related data (A81) is loaded once for every rule of the type.
        context = await context_for_event(session, event, related=related_for_rules(matching))
        for rule in matching:
            run = await _run_rule(
                session,
                tenant_id=tenant_id,
                rule=rule,
                event=event,
                context=context,
                settings=settings,
                now=now,
            )
            if run is None:
                continue
            totals["runs"] += 1
            if run.status == RUN_STATUS_FAILED:
                totals["failed"] += 1
    if events:
        watermark.last_occurred_at = events[-1].occurred_at
        watermark.last_event_id = events[-1].id
    watermark.updated_at = now
