"""A83: letters generated by a rule carry a visible draft notice; every other caller of the
letter renderer stays unchanged (notice off by default)."""

import io
from datetime import date

from pypdf import PdfReader

from mhvp.automation.services import DRAFT_NOTICE
from mhvp.documents import letters

HEAD = letters.Letterhead(
    company={
        "name": "Hausverwaltung Muster GmbH",
        "street": "Musterweg 1",
        "postal_code": "40789",
        "city": "Monheim am Rhein",
    },
    branding={},
)


def _text(pdf: bytes) -> str:
    return "\n".join((p.extract_text() or "") for p in PdfReader(io.BytesIO(pdf)).pages)


def _letter(**extra: object) -> letters.Letter:
    return letters.Letter(
        ["Frau Erika Muster", "Rheinpromenade 1", "40789 Monheim am Rhein"],
        "Eingangsbestätigung",
        "Wir haben Ihre Meldung erhalten.\n\n" + "Absatz.\n\n" * 60,
        date(2026, 9, 26),
        **extra,  # type: ignore[arg-type]
    )


def test_draft_notice_is_printed_on_every_page() -> None:
    notice = DRAFT_NOTICE.format(date="26.09.2026", rule="Eingang bestätigen")
    reader = PdfReader(io.BytesIO(letters.render_pdf(HEAD, _letter(draft_notice=notice))))
    assert len(reader.pages) > 1
    for page in reader.pages:
        text = page.extract_text() or ""
        assert "ENTWURF, automatisch erzeugt am 26.09.2026" in text
        assert "durch Regel Eingang bestätigen, nicht versendet" in text
        assert "ENTWURF" in text


def test_letter_without_draft_notice_is_unchanged() -> None:
    text = _text(letters.render_pdf(HEAD, _letter()))
    assert "ENTWURF" not in text
    assert "automatisch erzeugt" not in text
    assert "Eingangsbestätigung" in text
