"""Informationsblatt zur Betriebskostenabrechnung (7.6 A07 Satz 1, GA06-02).

A separate output beside the tenant letter: period, cost positions with their allocation
keys and bases, and the notes on Belegeinsicht and objections, read from the statement
snapshot only (A01, nothing recalculated). The note texts are placeholders of the operator
(docs/OPEN_QUESTIONS.md AA11-01, M17-05): no deadline or legal statement is generated by the
software; the deadline orientation of the statement is printed as orientation only. The sheet
is a draft (``draft_notice``); issuing stays behind G3 like the letters.
"""

import html
from datetime import date
from decimal import Decimal
from typing import Any

from mhvp.billing.letters import DRAFT_LABEL, fmt_date, fmt_eur
from mhvp.documents import letters

# GA06-02: marking of every legally relevant paragraph until AA11-01 is decided.
TEXT_NOT_RELEASED = "Text nicht freigegeben"
TEXT_CODES = ("info_sheet_inspection", "info_sheet_objection")  # AE16 text blocks
TEXT_PENDING = f"{TEXT_NOT_RELEASED}: Textbaustein des Betreibers ausstehend (AA11-01)"


def positions(snapshot_inputs: dict[str, Any]) -> list[dict[str, Any]]:
    """All cost positions of the statement with key and basis (no tenant share)."""
    out = []
    for position in snapshot_inputs.get("positions", []):
        key = position.get("allocation_key") or {}
        out.append(
            {
                "label": position["label"],
                "amount": str(position["amount"]),
                "allocation_key": key.get("name") or key.get("code") or "Einzelabrechnung",
                "basis": position.get("basis") or "",
            }
        )
    return out


def build(
    *,
    period_from: date,
    period_to: date,
    object_line: str,
    snapshot_inputs: dict[str, Any],
    snapshot_hash: str,
    version: int,
    letter_date: date,
    texts: dict[str, str] | None = None,
) -> letters.Letter:
    """Info sheet as a letter without recipient; ``texts`` are the operator's released
    paragraphs (``inspection``, ``objection``); missing texts print as pending placeholder."""
    texts = texts or {}
    rows = positions(snapshot_inputs)
    total = sum((Decimal(r["amount"]) for r in rows), Decimal("0.00"))
    table = letters.LetterTable(
        header=["Kostenart", "Verteilerschlüssel", "Gesamtkosten"],
        rows=[[r["label"], r["allocation_key"], fmt_eur(Decimal(r["amount"]))] for r in rows]
        + [["Summe", "", fmt_eur(total)]],
        right_aligned=(2,),
        total_row=True,
        widths=(0.45, 0.3, 0.25),
    )
    paragraphs = [
        html.escape(
            f"Informationsblatt zur Betriebskostenabrechnung für {object_line}, "
            f"Abrechnungszeitraum {fmt_date(period_from)} bis {fmt_date(period_to)}."
        ),
        letters.TABLE_MARKER.format(name="positionen"),
        html.escape(
            "Grundlagen der Verteilung: "
            + "; ".join(f"{r['label']}: {r['basis']}" for r in rows if r["basis"])
        )
        if any(r["basis"] for r in rows)
        else html.escape("Grundlagen der Verteilung: siehe Abrechnung."),
        html.escape("Belegeinsicht: " + (texts.get("inspection") or TEXT_PENDING) + "."),
        html.escape("Einwendungen: " + (texts.get("objection") or TEXT_PENDING) + "."),
    ]
    return letters.Letter(
        recipient_lines=[],
        subject=html.escape(
            f"Informationsblatt Betriebskostenabrechnung {fmt_date(period_from)} bis "
            f"{fmt_date(period_to)}"
        ),
        body="\n\n".join(paragraphs),
        letter_date=letter_date,
        info=[("Abrechnung", f"Version {version}, Stand {snapshot_hash[:12]}")],
        closing="",
        tables={"positionen": table},
        draft_notice=DRAFT_LABEL,
    )
