"""UUID version 7 (RFC 9562) primary keys and correlation ids.

Python 3.12 has no ``uuid.uuid7``. This implementation uses RFC 9562 section 6.2 method 1:
the 12 bit ``rand_a`` field is a counter that is seeded randomly for every new millisecond,
so ids generated by one process are strictly increasing, even within the same millisecond
and if the wall clock moves backwards.
"""

import os
import threading
import time
import uuid

_UNIX_TS_MS_MASK = (1 << 48) - 1
_COUNTER_MAX = 0xFFF
_COUNTER_SEED_MASK = 0x7FF  # leftmost counter bit stays 0 to leave room for increments
_RAND_B_MASK = (1 << 62) - 1

_lock = threading.Lock()
_last_ms = 0
_counter = 0


def _seed_counter() -> int:
    return int.from_bytes(os.urandom(2), "big") & _COUNTER_SEED_MASK


def uuid7() -> uuid.UUID:
    """Return a new, time ordered UUID v7."""
    global _last_ms, _counter
    with _lock:
        now_ms = time.time_ns() // 1_000_000
        if now_ms > _last_ms:
            _last_ms = now_ms
            _counter = _seed_counter()
        else:
            _counter += 1
            if _counter > _COUNTER_MAX:
                _last_ms += 1
                _counter = _seed_counter()
        unix_ts_ms, counter = _last_ms, _counter

    rand_b = int.from_bytes(os.urandom(8), "big") & _RAND_B_MASK
    value = (unix_ts_ms & _UNIX_TS_MS_MASK) << 80 | 0x7 << 76 | counter << 64 | 0b10 << 62 | rand_b
    return uuid.UUID(int=value)


def uuid7_timestamp_ms(value: uuid.UUID) -> int:
    """Return the Unix timestamp in milliseconds embedded in a UUID v7."""
    if value.version != 7:
        raise ValueError("not a UUID version 7")
    return value.int >> 80
