"use client";

import { useTranslations } from "next-intl";
import { useState } from "react";

import { bff } from "@/lib/bff";
import { ui } from "@/lib/ui";

/** Shape of GET/PATCH /api/v1/tenant/billing-settings (M13-04/M18-01). Not yet in the
 * generated api-client (openapi.json is not regenerated by this task); kept as a local type. */
export type BillingSettings = {
  tenant_id: string;
  invoice_prefix: string | null;
  vat_status: "unset" | "regelbesteuert" | "kleinunternehmer";
  vat_id_masked: string | null;
  tax_number_masked: string | null;
  leitweg_id: string | null;
  payee_iban_masked: string | null;
  kleinunternehmer_note: string | null;
  datev_consultant_number: string | null;
  datev_client_number: string | null;
  datev_chart_of_accounts: "unset" | "skr03" | "skr04";
  datev_account_length: number | null;
  datev_fiscal_year_start_month: number;
  version: number;
};

type Patch = Partial<
  Omit<
    BillingSettings,
    "tenant_id" | "vat_id_masked" | "tax_number_masked" | "payee_iban_masked" | "version"
  >
> & { vat_id?: string; tax_number?: string; payee_iban?: string };

const TEXT_FIELDS = [
  "invoice_prefix",
  "leitweg_id",
  "datev_consultant_number",
  "datev_client_number",
] as const;

export function BillingSettingsForm({
  initial,
  canUpdate,
}: {
  initial: BillingSettings;
  canUpdate: boolean;
}) {
  const t = useTranslations("BillingSettings");
  const [values, setValues] = useState(initial);
  const [patch, setPatch] = useState<Patch>({});
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  function set<K extends keyof Patch>(field: K, value: Patch[K]) {
    setPatch((prev) => ({ ...prev, [field]: value }));
  }

  function invalidFields(): string[] {
    const out: string[] = [];
    const prefix = patch.invoice_prefix;
    if (prefix && !/^[A-Z0-9]{2,16}$/.test(prefix)) out.push(t("validation.invoice_prefix"));
    const length = patch.datev_account_length;
    if (typeof length === "number" && (!Number.isInteger(length) || length < 4 || length > 8)) out.push(t("validation.datev_account_length"));
    const month = patch.datev_fiscal_year_start_month;
    if (typeof month === "number" && (!Number.isInteger(month) || month < 1 || month > 12)) out.push(t("validation.datev_fiscal_year_start_month"));
    return out;
  }

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setMessage(null);
    setError(null);
    const invalid = invalidFields();
    if (invalid.length) {
      setError(t("invalid", { fields: invalid.join(" ") }));
      return;
    }
    setBusy(true);
    const res = await bff<BillingSettings>("/api/bff/tenant/billing-settings", {
      method: "PATCH",
      body: JSON.stringify(patch),
    });
    setBusy(false);
    if (res.ok) {
      setValues(res.data);
      setPatch({});
      setMessage(t("saved"));
    } else {
      setError(res.message);
    }
  }

  return (
    <form onSubmit={(e) => void submit(e)} className={`${ui.card} grid gap-3 sm:grid-cols-2`}>
      <p className="sm:col-span-2 text-xs text-muted">{t("hint")}</p>
      {TEXT_FIELDS.map((field) => (
        <label key={field} className="flex flex-col gap-1">
          <span className={ui.label}>{t(`field.${field}`)}</span>
          <input
            className={ui.input}
            value={(patch[field] as string | undefined) ?? values[field] ?? ""}
            disabled={!canUpdate}
            onChange={(e) => set(field, e.target.value)}
          />
        </label>
      ))}
      <label className="flex flex-col gap-1">
        <span className={ui.label}>{t("field.vat_status")}</span>
        <select
          className={ui.input}
          value={(patch.vat_status as string | undefined) ?? values.vat_status}
          disabled={!canUpdate}
          onChange={(e) => set("vat_status", e.target.value as BillingSettings["vat_status"])}
        >
          <option value="unset">{t("field.vat_status_unset")}</option>
          <option value="regelbesteuert">{t("field.vat_status_regelbesteuert")}</option>
          <option value="kleinunternehmer">{t("field.vat_status_kleinunternehmer")}</option>
        </select>
      </label>
      <label className="flex flex-col gap-1">
        <span className={ui.label}>{t("field.vat_id")}</span>
        <input
          className={ui.input}
          placeholder={values.vat_id_masked ?? undefined}
          disabled={!canUpdate}
          onChange={(e) => set("vat_id", e.target.value)}
        />
        <span className="text-xs text-muted">{t("secretHint")}</span>
      </label>
      <label className="flex flex-col gap-1">
        <span className={ui.label}>{t("field.tax_number")}</span>
        <input
          className={ui.input}
          placeholder={values.tax_number_masked ?? undefined}
          disabled={!canUpdate}
          onChange={(e) => set("tax_number", e.target.value)}
        />
        <span className="text-xs text-muted">{t("secretHint")}</span>
      </label>
      <label className="flex flex-col gap-1">
        <span className={ui.label}>{t("field.payee_iban")}</span>
        <input
          className={ui.input}
          placeholder={values.payee_iban_masked ?? undefined}
          disabled={!canUpdate}
          onChange={(e) => set("payee_iban", e.target.value)}
        />
        <span className="text-xs text-muted">{t("secretHint")}</span>
      </label>
      <label className="sm:col-span-2 flex flex-col gap-1">
        <span className={ui.label}>{t("field.kleinunternehmer_note")}</span>
        <textarea
          className={ui.input}
          rows={3}
          value={(patch.kleinunternehmer_note as string | undefined) ?? values.kleinunternehmer_note ?? ""}
          disabled={!canUpdate}
          onChange={(e) => set("kleinunternehmer_note", e.target.value)}
        />
      </label>
      <label className="flex flex-col gap-1">
        <span className={ui.label}>{t("field.datev_chart_of_accounts")}</span>
        <select
          className={ui.input}
          value={(patch.datev_chart_of_accounts as string | undefined) ?? values.datev_chart_of_accounts}
          disabled={!canUpdate}
          onChange={(e) =>
            set("datev_chart_of_accounts", e.target.value as BillingSettings["datev_chart_of_accounts"])
          }
        >
          <option value="unset">{t("field.datev_chart_of_accounts_unset")}</option>
          <option value="skr03">{t("field.datev_chart_of_accounts_skr03")}</option>
          <option value="skr04">{t("field.datev_chart_of_accounts_skr04")}</option>
        </select>
      </label>
      <label className="flex flex-col gap-1">
        <span className={ui.label}>{t("field.datev_account_length")}</span>
        <input
          type="number"
          min={4}
          max={8}
          className={ui.input}
          value={(patch.datev_account_length as number | undefined) ?? values.datev_account_length ?? ""}
          disabled={!canUpdate}
          onChange={(e) => set("datev_account_length", e.target.value ? Number(e.target.value) : undefined)}
        />
        <span className="text-xs text-muted">{t("validation.datev_account_length")}</span>
      </label>
      <label className="flex flex-col gap-1">
        <span className={ui.label}>{t("field.datev_fiscal_year_start_month")}</span>
        <input
          type="number"
          min={1}
          max={12}
          className={ui.input}
          value={
            (patch.datev_fiscal_year_start_month as number | undefined) ??
            values.datev_fiscal_year_start_month
          }
          disabled={!canUpdate}
          onChange={(e) => set("datev_fiscal_year_start_month", Number(e.target.value))}
        />
        <span className="text-xs text-muted">{t("validation.datev_fiscal_year_start_month")}</span>
      </label>
      {canUpdate ? (
        <div className="sm:col-span-2 flex flex-col gap-2">
          <div className={ui.formActions}>
            <button type="submit" className={`${ui.primary} ${ui.actionFull}`} disabled={busy}>
              {t("save")}
            </button>
          </div>
          {message ? (
            <p role="status" className={ui.success}>
              {message}
            </p>
          ) : null}
          {error ? (
            <p role="alert" className={ui.alert}>
              {error}
            </p>
          ) : null}
        </div>
      ) : (
        <p className="sm:col-span-2 text-xs text-muted">{t("readOnly")}</p>
      )}
    </form>
  );
}
