"""contacts parties consents

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-23 08:05:53.499939+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TENANT_TABLES = (
    "contact",
    "contact_tag",
    "party",
    "consent",
    "contact_address",
    "contact_bank_account",
    "contact_email",
    "contact_identifier",
    "contact_note",
    "contact_phone",
    "contact_relation",
    "contact_tag_link",
    "contact_type",
    "party_member",
)
ENUMS = (
    "address_label",
    "consent_kind",
    "contact_completeness",
    "contact_kind",
    "contact_type_code",
    "identifier_kind",
    "party_role",
    "phone_label",
    "preferred_channel",
    "relation_kind",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("kind", sa.Enum("person", "company", name="contact_kind"), nullable=False),
        sa.Column("salutation", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("legal_form", sa.String(length=50), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "preferred_channel",
            sa.Enum("post", "email", "portal", name="preferred_channel"),
            nullable=True,
        ),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "completeness",
            sa.Enum("complete", "incomplete", name="contact_completeness"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', search_text)", persisted=True),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    op.create_index(
        "ix_contact_search_text_trgm",
        "contact",
        ["search_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_contact_search_vector",
        "contact",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_contact_tenant_id_last_name", "contact", ["tenant_id", "last_name"], unique=False
    )
    op.create_table(
        "contact_tag",
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_tag_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_tag")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_contact_tag_tenant_id_name")),
    )
    op.create_table(
        "party",
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_party_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party")),
    )
    op.create_table(
        "consent",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "data_sharing", "portal_terms", "email_delivery", "marketing", name="consent_kind"
            ),
            nullable=False,
        ),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_consent_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_consent_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent")),
    )
    op.create_index(op.f("ix_consent_contact_id"), "consent", ["contact_id"], unique=False)
    op.create_table(
        "contact_address",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "label",
            sa.Enum("postal", "private", "work", "public", name="address_label"),
            nullable=False,
        ),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("house_number", sa.String(length=20), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("addition", sa.String(length=200), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_address_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_address_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_address")),
    )
    op.create_index(
        op.f("ix_contact_address_contact_id"), "contact_address", ["contact_id"], unique=False
    )
    op.create_table(
        "contact_bank_account",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("iban", sa.LargeBinary(), nullable=False),
        sa.Column("iban_suffix", sa.String(length=4), nullable=False),
        sa.Column("iban_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("bic", sa.String(length=11), nullable=True),
        sa.Column("bank_name", sa.String(length=200), nullable=True),
        sa.Column("holder", sa.String(length=200), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_bank_account_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_bank_account_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_bank_account")),
    )
    op.create_index(
        op.f("ix_contact_bank_account_contact_id"),
        "contact_bank_account",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_bank_account_iban_fingerprint"),
        "contact_bank_account",
        ["iban_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_contact_bank_account_tenant_id_iban_suffix",
        "contact_bank_account",
        ["tenant_id", "iban_suffix"],
        unique=False,
    )
    op.create_table(
        "contact_email",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_portal_login", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_email_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_email_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_email")),
    )
    op.create_index(
        op.f("ix_contact_email_contact_id"), "contact_email", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_contact_email_tenant_id_email", "contact_email", ["tenant_id", "email"], unique=False
    )
    op.create_table(
        "contact_identifier",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "tax_number",
                "vat_id",
                "sepa_creditor_id",
                "registry_number",
                "customer_number",
                name="identifier_kind",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_identifier_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_identifier_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_identifier")),
    )
    op.create_index(
        op.f("ix_contact_identifier_contact_id"), "contact_identifier", ["contact_id"], unique=False
    )
    op.create_table(
        "contact_note",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=63), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_note_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_note_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_note")),
    )
    op.create_index(
        op.f("ix_contact_note_contact_id"), "contact_note", ["contact_id"], unique=False
    )
    op.create_table(
        "contact_phone",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "label",
            sa.Enum("work", "mobile", "private", "fax", "other", name="phone_label"),
            nullable=False,
        ),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_phone_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_phone_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_phone")),
    )
    op.create_index(
        op.f("ix_contact_phone_contact_id"), "contact_phone", ["contact_id"], unique=False
    )
    op.create_table(
        "contact_relation",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("related_contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "spouse",
                "representative",
                "heir",
                "guarantor",
                "employee_of",
                "authorized_person",
                name="relation_kind",
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_relation_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["related_contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_relation_related_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_relation_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_relation")),
    )
    op.create_index(
        op.f("ix_contact_relation_contact_id"), "contact_relation", ["contact_id"], unique=False
    )
    op.create_table(
        "contact_tag_link",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_tag_link_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["contact_tag.id"],
            name=op.f("fk_contact_tag_link_tag_id_contact_tag"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_tag_link_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_tag_link")),
        sa.UniqueConstraint(
            "tenant_id",
            "contact_id",
            "tag_id",
            name=op.f("uq_contact_tag_link_tenant_id_contact_id_tag_id"),
        ),
    )
    op.create_index(
        op.f("ix_contact_tag_link_contact_id"), "contact_tag_link", ["contact_id"], unique=False
    )
    op.create_table(
        "contact_type",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "tenant",
                "prospect",
                "owner",
                "service_provider",
                "broker",
                "manager",
                "bank",
                "board_member",
                "authority",
                "other",
                name="contact_type_code",
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_type_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_contact_type_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_type")),
        sa.UniqueConstraint(
            "tenant_id",
            "contact_id",
            "type",
            name=op.f("uq_contact_type_tenant_id_contact_id_type"),
        ),
    )
    op.create_index(
        op.f("ix_contact_type_contact_id"), "contact_type", ["contact_id"], unique=False
    )
    op.create_table(
        "party_member",
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("primary", "co_party", "guarantor", "legal_representative", name="party_role"),
            nullable=False,
        ),
        sa.Column("share_percent", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_party_member_contact_id_contact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_party_member_party_id_party"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_party_member_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party_member")),
        sa.UniqueConstraint(
            "tenant_id",
            "party_id",
            "contact_id",
            name=op.f("uq_party_member_tenant_id_party_id_contact_id"),
        ),
    )
    op.create_index(
        op.f("ix_party_member_contact_id"), "party_member", ["contact_id"], unique=False
    )
    op.create_index(op.f("ix_party_member_party_id"), "party_member", ["party_id"], unique=False)
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_party_member_party_id"), table_name="party_member")
    op.drop_index(op.f("ix_party_member_contact_id"), table_name="party_member")
    op.drop_table("party_member")
    op.drop_index(op.f("ix_contact_type_contact_id"), table_name="contact_type")
    op.drop_table("contact_type")
    op.drop_index(op.f("ix_contact_tag_link_contact_id"), table_name="contact_tag_link")
    op.drop_table("contact_tag_link")
    op.drop_index(op.f("ix_contact_relation_contact_id"), table_name="contact_relation")
    op.drop_table("contact_relation")
    op.drop_index(op.f("ix_contact_phone_contact_id"), table_name="contact_phone")
    op.drop_table("contact_phone")
    op.drop_index(op.f("ix_contact_note_contact_id"), table_name="contact_note")
    op.drop_table("contact_note")
    op.drop_index(op.f("ix_contact_identifier_contact_id"), table_name="contact_identifier")
    op.drop_table("contact_identifier")
    op.drop_index("ix_contact_email_tenant_id_email", table_name="contact_email")
    op.drop_index(op.f("ix_contact_email_contact_id"), table_name="contact_email")
    op.drop_table("contact_email")
    op.drop_index(
        "ix_contact_bank_account_tenant_id_iban_suffix", table_name="contact_bank_account"
    )
    op.drop_index(
        op.f("ix_contact_bank_account_iban_fingerprint"), table_name="contact_bank_account"
    )
    op.drop_index(op.f("ix_contact_bank_account_contact_id"), table_name="contact_bank_account")
    op.drop_table("contact_bank_account")
    op.drop_index(op.f("ix_contact_address_contact_id"), table_name="contact_address")
    op.drop_table("contact_address")
    op.drop_index(op.f("ix_consent_contact_id"), table_name="consent")
    op.drop_table("consent")
    op.drop_table("party")
    op.drop_table("contact_tag")
    op.drop_index("ix_contact_tenant_id_last_name", table_name="contact")
    op.drop_index("ix_contact_search_vector", table_name="contact", postgresql_using="gin")
    op.drop_index(
        "ix_contact_search_text_trgm",
        table_name="contact",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_table("contact")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
