"""properties units legal entities

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-23 08:15:18.360618+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TENANT_TABLES = (
    "allocation_key_template",
    "catalog_entry",
    "custom_field_definition",
    "property",
    "allocation_key",
    "building",
    "legal_entity",
    "property_contact",
    "property_owner",
    "property_bank_account",
    "service_provider_relation",
    "unit",
    "maintenance_item",
    "meter",
    "unit_allocation_value",
    "unit_vat_option",
    "meter_reading",
)
ENUMS = (
    "allocation_kind",
    "bank_account_kind",
    "legal_entity_kind",
    "maintenance_kind",
    "management_mode",
    "management_type",
    "meter_connection",
    "property_status",
    "reading_source",
    "unit_type",
    "value_source",
    "vat_occupant",
    "vat_option",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_key_template",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=16), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("static", "consumption", "fixed_amount", "fixed_share", name="allocation_kind"),
            nullable=False,
        ),
        sa.Column("meter_type_code", sa.String(length=63), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_allocation_key_template_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_key_template")),
        sa.UniqueConstraint(
            "tenant_id", "code", name=op.f("uq_allocation_key_template_tenant_id_code")
        ),
    )
    op.create_table(
        "catalog_entry",
        sa.Column("catalog", sa.String(length=63), nullable=False),
        sa.Column("code", sa.String(length=63), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_catalog_entry_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_entry")),
        sa.UniqueConstraint(
            "tenant_id", "catalog", "code", name=op.f("uq_catalog_entry_tenant_id_catalog_code")
        ),
    )
    op.create_table(
        "custom_field_definition",
        sa.Column("entity_type", sa.String(length=63), nullable=False),
        sa.Column("key", sa.String(length=63), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("field_type", sa.String(length=16), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_custom_field_definition_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_field_definition")),
        sa.UniqueConstraint(
            "tenant_id",
            "entity_type",
            "key",
            name=op.f("uq_custom_field_definition_tenant_id_entity_type_key"),
        ),
    )
    op.create_table(
        "property",
        sa.Column("number", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "management_type",
            sa.Enum("rental", "hoa", "hoa_with_sev", name="management_type"),
            nullable=False,
        ),
        sa.Column(
            "management_mode", sa.Enum("own", "third_party", name="management_mode"), nullable=False
        ),
        sa.Column("property_type_code", sa.String(length=63), nullable=True),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("house_number", sa.String(length=20), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("municipality_code", sa.String(length=20), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("land_registry_district", sa.String(length=100), nullable=True),
        sa.Column("land_registry_sheet", sa.String(length=50), nullable=True),
        sa.Column("parcel", sa.String(length=200), nullable=True),
        sa.Column("built_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("unbuilt_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("sealed_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("garden_use", sa.String(length=16), nullable=True),
        sa.Column("garden_notes", sa.Text(), nullable=True),
        sa.Column("renovation_flag", sa.Boolean(), nullable=False),
        sa.Column("renovation_notes", sa.Text(), nullable=True),
        sa.Column("allocation_loss_risk_percent", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("manager_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("onboarding", "active", "terminated", name="property_status"),
            nullable=False,
        ),
        sa.Column("managed_from", sa.Date(), nullable=True),
        sa.Column("managed_to", sa.Date(), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("number ~ '^[0-9]{3}$'", name=op.f("ck_property_number_format")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_property_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_property_tenant_id_number")),
    )
    op.create_table(
        "allocation_key",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=16), nullable=False),
        sa.Column("default_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("static", "consumption", "fixed_amount", "fixed_share", name="allocation_kind"),
            nullable=False,
        ),
        sa.Column("meter_type_code", sa.String(length=63), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_template_derived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_allocation_key_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_allocation_key_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_key")),
        sa.UniqueConstraint(
            "tenant_id",
            "property_id",
            "code",
            name=op.f("uq_allocation_key_tenant_id_property_id_code"),
        ),
    )
    op.create_index(
        op.f("ix_allocation_key_property_id"), "allocation_key", ["property_id"], unique=False
    )
    op.create_table(
        "building",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("house_number", sa.String(length=20), nullable=True),
        sa.Column("built_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("sealed_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("roof_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("construction_year", sa.Integer(), nullable=True),
        sa.Column("renovation_level", sa.String(length=100), nullable=True),
        sa.Column("construction_type_code", sa.String(length=63), nullable=True),
        sa.Column("building_type_code", sa.String(length=63), nullable=True),
        sa.Column("floors", sa.Integer(), nullable=True),
        sa.Column("windows", sa.Integer(), nullable=True),
        sa.Column("total_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("living_commercial_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("heated_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("window_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("hallway_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("gross_floor_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("elevator", sa.Boolean(), nullable=False),
        sa.Column("cellar_rooms", sa.Integer(), nullable=True),
        sa.Column("heritage_protection", sa.Boolean(), nullable=False),
        sa.Column("heritage_notes", sa.Text(), nullable=True),
        sa.Column("energy_certificate_type", sa.String(length=32), nullable=True),
        sa.Column("energy_certificate_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("energy_certificate_valid_until", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_building_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_building_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building")),
    )
    op.create_index(op.f("ix_building_property_id"), "building", ["property_id"], unique=False)
    op.create_table(
        "legal_entity",
        sa.Column(
            "kind",
            sa.Enum("hoa", "rental_owner", "sev_owner", "manager", name="legal_entity_kind"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=True),
        sa.Column("property_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_legal_entity_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_legal_entity_property_id_property"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_legal_entity_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_entity")),
    )
    op.create_index(op.f("ix_legal_entity_party_id"), "legal_entity", ["party_id"], unique=False)
    op.create_index(
        op.f("ix_legal_entity_property_id"), "legal_entity", ["property_id"], unique=False
    )
    op.create_index(
        "uq_legal_entity_hoa_per_property",
        "legal_entity",
        ["tenant_id", "property_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'hoa'"),
    )
    op.create_table(
        "property_contact",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("category_code", sa.String(length=63), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("visible_in_portal_for", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_property_contact_contact_id_contact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_property_contact_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_property_contact_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_contact")),
    )
    op.create_index(
        op.f("ix_property_contact_contact_id"), "property_contact", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_property_contact_property_id"), "property_contact", ["property_id"], unique=False
    )
    op.create_table(
        "property_owner",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("share_percent", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_property_owner_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_property_owner_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_property_owner_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_owner")),
    )
    op.create_index(
        op.f("ix_property_owner_party_id"), "property_owner", ["party_id"], unique=False
    )
    op.create_index(
        op.f("ix_property_owner_property_id"), "property_owner", ["property_id"], unique=False
    )
    op.create_table(
        "property_bank_account",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("legal_entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "rent", "hoa", "reserve", "deposit", "hoa_fee", "other", name="bank_account_kind"
            ),
            nullable=False,
        ),
        sa.Column("iban", sa.LargeBinary(), nullable=False),
        sa.Column("iban_suffix", sa.String(length=4), nullable=False),
        sa.Column("iban_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("bic", sa.String(length=11), nullable=True),
        sa.Column("bank_name", sa.String(length=200), nullable=True),
        sa.Column("holder", sa.String(length=200), nullable=False),
        sa.Column("segregated", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "kind <> 'deposit' OR segregated",
            name=op.f("ck_property_bank_account_deposit_segregated"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_property_bank_account_period_order"),
        ),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entity.id"],
            name=op.f("fk_property_bank_account_legal_entity_id_legal_entity"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_property_bank_account_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_property_bank_account_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_bank_account")),
    )
    op.create_index(
        op.f("ix_property_bank_account_iban_fingerprint"),
        "property_bank_account",
        ["iban_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_bank_account_legal_entity_id"),
        "property_bank_account",
        ["legal_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_bank_account_property_id"),
        "property_bank_account",
        ["property_id"],
        unique=False,
    )
    op.create_table(
        "service_provider_relation",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("contract_type_code", sa.String(length=63), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("notice_period", sa.String(length=100), nullable=True),
        sa.Column("contact_bank_account_id", sa.UUID(), nullable=True),
        sa.Column("create_default_bank_rule", sa.Boolean(), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_bank_account_id"],
            ["contact_bank_account.id"],
            name=op.f("fk_service_provider_relation_contact_bank_account_id_contact_bank_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_service_provider_relation_contact_id_contact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_service_provider_relation_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_service_provider_relation_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_provider_relation")),
    )
    op.create_index(
        op.f("ix_service_provider_relation_contact_bank_account_id"),
        "service_provider_relation",
        ["contact_bank_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_provider_relation_contact_id"),
        "service_provider_relation",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_provider_relation_property_id"),
        "service_provider_relation",
        ["property_id"],
        unique=False,
    )
    op.create_table(
        "unit",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("building_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column(
            "unit_type",
            sa.Enum(
                "apartment",
                "commercial",
                "office",
                "parking",
                "garage",
                "storage",
                "garden",
                "other",
                name="unit_type",
            ),
            nullable=False,
        ),
        sa.Column("internal_name", sa.String(length=200), nullable=True),
        sa.Column("rooms", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("total_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("living_area_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("floor", sa.String(length=20), nullable=True),
        sa.Column("last_modernization_year", sa.Integer(), nullable=True),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("cellar_number", sa.String(length=20), nullable=True),
        sa.Column("features", sa.Text(), nullable=True),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("house_number", sa.String(length=20), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["building.id"],
            name=op.f("fk_unit_building_id_building"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_unit_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_unit_tenant_id_tenant"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit")),
        sa.UniqueConstraint(
            "tenant_id", "property_id", "number", name=op.f("uq_unit_tenant_id_property_id_number")
        ),
    )
    op.create_index(op.f("ix_unit_building_id"), "unit", ["building_id"], unique=False)
    op.create_index(op.f("ix_unit_property_id"), "unit", ["property_id"], unique=False)
    op.create_table(
        "maintenance_item",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "modernization", "maintenance", "inspection", "warranty", name="maintenance_kind"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("remind_before", sa.String(length=8), nullable=True),
        sa.Column("interval_months", sa.Integer(), nullable=True),
        sa.Column("provider_relation_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_maintenance_item_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_relation_id"],
            ["service_provider_relation.id"],
            name=op.f("fk_maintenance_item_provider_relation_id_service_provider_relation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_maintenance_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
            name=op.f("fk_maintenance_item_unit_id_unit"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_item")),
    )
    op.create_index(
        op.f("ix_maintenance_item_property_id"), "maintenance_item", ["property_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_item_provider_relation_id"),
        "maintenance_item",
        ["provider_relation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_item_unit_id"), "maintenance_item", ["unit_id"], unique=False
    )
    op.create_table(
        "meter",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=True),
        sa.Column("meter_type_code", sa.String(length=63), nullable=False),
        sa.Column("number", sa.String(length=100), nullable=False),
        sa.Column("malo_id", sa.String(length=33), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("connection", sa.Enum("main", "sub", name="meter_connection"), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("calibration_due_date", sa.Date(), nullable=True),
        sa.Column("remote_readable", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_meter_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_meter_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["unit.id"], name=op.f("fk_meter_unit_id_unit"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter")),
    )
    op.create_index(op.f("ix_meter_property_id"), "meter", ["property_id"], unique=False)
    op.create_index(op.f("ix_meter_unit_id"), "meter", ["unit_id"], unique=False)
    op.create_table(
        "unit_allocation_value",
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("allocation_key_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("manual", "contract", "import", "ai", name="value_source"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("unit_id"), "="),
            (sa.column("allocation_key_id"), "="),
            (sa.text("daterange(valid_from, valid_to, '[]')"), "&&"),
            using="gist",
            name="ex_unit_allocation_value_period",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_unit_allocation_value_period_order"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_key_id"],
            ["allocation_key.id"],
            name=op.f("fk_unit_allocation_value_allocation_key_id_allocation_key"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_unit_allocation_value_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
            name=op.f("fk_unit_allocation_value_unit_id_unit"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_allocation_value")),
    )
    op.create_index(
        op.f("ix_unit_allocation_value_allocation_key_id"),
        "unit_allocation_value",
        ["allocation_key_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unit_allocation_value_unit_id"), "unit_allocation_value", ["unit_id"], unique=False
    )
    op.create_table(
        "unit_vat_option",
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column(
            "option",
            sa.Enum(
                "none",
                "commercial_no_vat",
                "commercial_full_vat",
                "commercial_reduced_vat",
                name="vat_option",
            ),
            nullable=False,
        ),
        sa.Column("occupant", sa.Enum("vacancy", "contract", name="vat_occupant"), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("unit_id"), "="),
            (sa.text("daterange(valid_from, valid_to, '[]')"), "&&"),
            using="gist",
            name="ex_unit_vat_option_period",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_unit_vat_option_period_order"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_unit_vat_option_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
            name=op.f("fk_unit_vat_option_unit_id_unit"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_vat_option")),
    )
    op.create_index(
        op.f("ix_unit_vat_option_unit_id"), "unit_vat_option", ["unit_id"], unique=False
    )
    op.create_table(
        "meter_reading",
        sa.Column("meter_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("manual", "portal", "provider_import", "ai", name="reading_source"),
            nullable=False,
        ),
        sa.Column("photo_document_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meter.id"],
            name=op.f("fk_meter_reading_meter_id_meter"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_meter_reading_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_reading")),
    )
    op.create_index(op.f("ix_meter_reading_meter_id"), "meter_reading", ["meter_id"], unique=False)
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meter_reading_meter_id"), table_name="meter_reading")
    op.drop_table("meter_reading")
    op.drop_index(op.f("ix_unit_vat_option_unit_id"), table_name="unit_vat_option")
    op.drop_table("unit_vat_option")
    op.drop_index(op.f("ix_unit_allocation_value_unit_id"), table_name="unit_allocation_value")
    op.drop_index(
        op.f("ix_unit_allocation_value_allocation_key_id"), table_name="unit_allocation_value"
    )
    op.drop_table("unit_allocation_value")
    op.drop_index(op.f("ix_meter_unit_id"), table_name="meter")
    op.drop_index(op.f("ix_meter_property_id"), table_name="meter")
    op.drop_table("meter")
    op.drop_index(op.f("ix_maintenance_item_unit_id"), table_name="maintenance_item")
    op.drop_index(op.f("ix_maintenance_item_provider_relation_id"), table_name="maintenance_item")
    op.drop_index(op.f("ix_maintenance_item_property_id"), table_name="maintenance_item")
    op.drop_table("maintenance_item")
    op.drop_index(op.f("ix_unit_property_id"), table_name="unit")
    op.drop_index(op.f("ix_unit_building_id"), table_name="unit")
    op.drop_table("unit")
    op.drop_index(
        op.f("ix_service_provider_relation_property_id"), table_name="service_provider_relation"
    )
    op.drop_index(
        op.f("ix_service_provider_relation_contact_id"), table_name="service_provider_relation"
    )
    op.drop_index(
        op.f("ix_service_provider_relation_contact_bank_account_id"),
        table_name="service_provider_relation",
    )
    op.drop_table("service_provider_relation")
    op.drop_index(op.f("ix_property_bank_account_property_id"), table_name="property_bank_account")
    op.drop_index(
        op.f("ix_property_bank_account_legal_entity_id"), table_name="property_bank_account"
    )
    op.drop_index(
        op.f("ix_property_bank_account_iban_fingerprint"), table_name="property_bank_account"
    )
    op.drop_table("property_bank_account")
    op.drop_index(op.f("ix_property_owner_property_id"), table_name="property_owner")
    op.drop_index(op.f("ix_property_owner_party_id"), table_name="property_owner")
    op.drop_table("property_owner")
    op.drop_index(op.f("ix_property_contact_property_id"), table_name="property_contact")
    op.drop_index(op.f("ix_property_contact_contact_id"), table_name="property_contact")
    op.drop_table("property_contact")
    op.drop_index(
        "uq_legal_entity_hoa_per_property",
        table_name="legal_entity",
        postgresql_where=sa.text("kind = 'hoa'"),
    )
    op.drop_index(op.f("ix_legal_entity_property_id"), table_name="legal_entity")
    op.drop_index(op.f("ix_legal_entity_party_id"), table_name="legal_entity")
    op.drop_table("legal_entity")
    op.drop_index(op.f("ix_building_property_id"), table_name="building")
    op.drop_table("building")
    op.drop_index(op.f("ix_allocation_key_property_id"), table_name="allocation_key")
    op.drop_table("allocation_key")
    op.drop_table("property")
    op.drop_table("custom_field_definition")
    op.drop_table("catalog_entry")
    op.drop_table("allocation_key_template")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
