"""documents

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-23 09:19:39.531386+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TENANT_TABLES = (
    "dms_connection",
    "document_category",
    "retention_profile",
    "document",
    "document_template",
    "document_link",
    "document_mirror",
)
ENUMS = (
    "storage_kind",
    "retention_start",
    "text_status",
    "document_source",
    "link_role",
    "mirror_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dms_connection",
        sa.Column(
            "kind",
            sa.Enum("minio", "paperless", "google_drive", name="storage_kind"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("secret", sa.LargeBinary(), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_dms_connection_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dms_connection")),
        sa.UniqueConstraint("tenant_id", "kind", name=op.f("uq_dms_connection_tenant_id_kind")),
    )
    op.create_table(
        "document_category",
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("paperless_document_type", sa.String(length=128), nullable=True),
        sa.Column("drive_folder", sa.String(length=64), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["document_category.id"],
            name=op.f("fk_document_category_parent_id_document_category"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_category_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_category")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_document_category_tenant_id_code")),
    )
    op.create_index(
        op.f("ix_document_category_parent_id"), "document_category", ["parent_id"], unique=False
    )
    op.create_table(
        "retention_profile",
        sa.Column("document_class", sa.String(length=63), nullable=False),
        sa.Column("legal_entity_kind", sa.String(length=32), nullable=True),
        sa.Column("legal_basis", sa.Text(), nullable=False),
        sa.Column("retention_years", sa.Integer(), nullable=False),
        sa.Column(
            "start_rule",
            sa.Enum(
                "end_of_year_created",
                "end_of_year_last_entry",
                "contract_end",
                "statement_issued",
                name="retention_start",
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(released_at IS NULL) = (released_by IS NULL)",
            name=op.f("ck_retention_profile_release_complete"),
        ),
        sa.CheckConstraint("retention_years > 0", name=op.f("ck_retention_profile_years_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_retention_profile_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_profile")),
        sa.UniqueConstraint(
            "tenant_id",
            "document_class",
            "legal_entity_kind",
            name=op.f("uq_retention_profile_tenant_id_document_class_legal_entity_kind"),
        ),
    )
    op.create_table(
        "document",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "storage",
            sa.Enum("minio", "paperless", "google_drive", name="storage_kind"),
            nullable=False,
        ),
        sa.Column("storage_ref", sa.String(length=512), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column(
            "text_status",
            sa.Enum("extracted", "pending", "none", name="text_status"),
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('german', coalesce(title, '') || ' ' || coalesce(filename, '') "
                "|| ' ' || coalesce(ocr_text, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "upload", "generated", "email", "scan", "portal", "import", name="document_source"
            ),
            nullable=False,
        ),
        sa.Column("retention_profile_id", sa.UUID(), nullable=True),
        sa.Column("retention_until", sa.Date(), nullable=True),
        sa.Column("retention_hold_reason", sa.Text(), nullable=True),
        sa.Column("visibility", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("size >= 0", name=op.f("ck_document_size_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["document_category.id"],
            name=op.f("fk_document_category_id_document_category"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["retention_profile_id"],
            ["retention_profile.id"],
            name=op.f("fk_document_retention_profile_id_retention_profile"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
    )
    op.create_index(op.f("ix_document_category_id"), "document", ["category_id"], unique=False)
    op.create_index(
        op.f("ix_document_retention_profile_id"), "document", ["retention_profile_id"], unique=False
    )
    op.create_index(
        "ix_document_search_vector",
        "document",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_document_tenant_sha256", "document", ["tenant_id", "sha256"], unique=False)
    op.create_index(
        "ix_document_title_trgm",
        "document",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "document_template",
        sa.Column("code", sa.String(length=63), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["document_category.id"],
            name=op.f("fk_document_template_category_id_document_category"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_template_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_template")),
        sa.UniqueConstraint(
            "tenant_id", "code", "version", name=op.f("uq_document_template_tenant_id_code_version")
        ),
    )
    op.create_index(
        op.f("ix_document_template_category_id"), "document_template", ["category_id"], unique=False
    )
    op.create_table(
        "document_link",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=63), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("attachment", "evidence", "original", "generated", name="link_role"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_link_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_link_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_link")),
        sa.UniqueConstraint(
            "tenant_id",
            "document_id",
            "entity_type",
            "entity_id",
            "role",
            name=op.f("uq_document_link_tenant_id_document_id_entity_type_entity_id_role"),
        ),
    )
    op.create_index(
        op.f("ix_document_link_document_id"), "document_link", ["document_id"], unique=False
    )
    op.create_index(
        "ix_document_link_entity",
        "document_link",
        ["tenant_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "document_mirror",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("minio", "paperless", "google_drive", name="storage_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "submitted", "done", "failed", name="mirror_status"),
            nullable=False,
        ),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_mirror_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_mirror_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_mirror")),
        sa.UniqueConstraint(
            "tenant_id",
            "document_id",
            "kind",
            name=op.f("uq_document_mirror_tenant_id_document_id_kind"),
        ),
    )
    op.create_index(
        op.f("ix_document_mirror_document_id"), "document_mirror", ["document_id"], unique=False
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_mirror_document_id"), table_name="document_mirror")
    op.drop_table("document_mirror")
    op.drop_index("ix_document_link_entity", table_name="document_link")
    op.drop_index(op.f("ix_document_link_document_id"), table_name="document_link")
    op.drop_table("document_link")
    op.drop_index(op.f("ix_document_template_category_id"), table_name="document_template")
    op.drop_table("document_template")
    op.drop_index(
        "ix_document_title_trgm",
        table_name="document",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index("ix_document_tenant_sha256", table_name="document")
    op.drop_index("ix_document_search_vector", table_name="document", postgresql_using="gin")
    op.drop_index(op.f("ix_document_retention_profile_id"), table_name="document")
    op.drop_index(op.f("ix_document_category_id"), table_name="document")
    op.drop_table("document")
    op.drop_table("retention_profile")
    op.drop_index(op.f("ix_document_category_parent_id"), table_name="document_category")
    op.drop_table("document_category")
    op.drop_table("dms_connection")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
