"""ai gateway

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-23 09:54:51.868215+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TENANT_TABLES = (
    "ai_provider_config",
    "ai_conversation",
    "ai_task_run",
    "import_run",
    "import_run_item",
    "ai_proposal",
    "ai_example",
    "ai_message",
)
ENUMS = ("ai_provider", "ai_task", "ai_run_status", "ai_decision", "import_status")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_conversation",
        sa.Column("context_type", sa.String(length=32), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_conversation_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_conversation")),
    )
    op.create_table(
        "import_run",
        sa.Column("source", sa.String(length=63), nullable=False),
        sa.Column(
            "status",
            sa.Enum("applied", "undone", "partially_undone", name="import_status"),
            nullable=False,
        ),
        sa.Column("document_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_import_run_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_run")),
    )
    op.create_table(
        "ai_task_run",
        sa.Column(
            "task",
            sa.Enum(
                "extract_contacts",
                "extract_property",
                "classify_email",
                "propose_posting",
                "extract_invoice",
                "draft_reply",
                "check_statement",
                "answer_question",
                "summarize",
                name="ai_task",
            ),
            nullable=False,
        ),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.Enum("anthropic", "openai", name="ai_provider"), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_eur", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "blocked", name="ai_run_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversation.id"],
            name=op.f("fk_ai_task_run_conversation_id_ai_conversation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_task_run_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_task_run")),
    )
    op.create_index(
        op.f("ix_ai_task_run_conversation_id"), "ai_task_run", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_ai_task_run_input_hash",
        "ai_task_run",
        ["tenant_id", "task", "input_hash"],
        unique=False,
    )
    op.create_table(
        "import_run_item",
        sa.Column("import_run_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=63), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("undone", sa.Boolean(), nullable=False),
        sa.Column("kept_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_run.id"],
            name=op.f("fk_import_run_item_import_run_id_import_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_import_run_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_run_item")),
    )
    op.create_index(
        op.f("ix_import_run_item_import_run_id"), "import_run_item", ["import_run_id"], unique=False
    )
    op.create_table(
        "ai_proposal",
        sa.Column("task_run_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=63), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.Column("proposed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("pending", "accepted", "modified", "rejected", name="ai_decision"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("final", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("import_run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_run.id"],
            name=op.f("fk_ai_proposal_import_run_id_import_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["ai_task_run.id"],
            name=op.f("fk_ai_proposal_task_run_id_ai_task_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_proposal_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_proposal")),
    )
    op.create_index(
        op.f("ix_ai_proposal_import_run_id"), "ai_proposal", ["import_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_proposal_task_run_id"), "ai_proposal", ["task_run_id"], unique=False
    )
    op.create_table(
        "ai_provider_config",
        sa.Column("provider", sa.Enum("anthropic", "openai", name="ai_provider"), nullable=False),
        sa.Column("api_key", sa.LargeBinary(), nullable=True),
        sa.Column("models", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("task_tiers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("monthly_budget_eur", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("data_processing_agreement_signed", sa.Boolean(), nullable=False),
        sa.Column("dpa_document_id", sa.UUID(), nullable=True),
        sa.Column("training_opt_out_confirmed", sa.Boolean(), nullable=False),
        sa.Column("endpoint_region", sa.String(length=32), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(released_at IS NULL) = (released_by IS NULL)",
            name=op.f("ck_ai_provider_config_release_complete"),
        ),
        sa.CheckConstraint(
            "monthly_budget_eur >= 0", name=op.f("ck_ai_provider_config_budget_positive")
        ),
        sa.ForeignKeyConstraint(
            ["dpa_document_id"],
            ["document.id"],
            name=op.f("fk_ai_provider_config_dpa_document_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_provider_config_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_provider_config")),
        sa.UniqueConstraint(
            "tenant_id", "provider", name=op.f("uq_ai_provider_config_tenant_id_provider")
        ),
    )
    op.create_index(
        op.f("ix_ai_provider_config_dpa_document_id"),
        "ai_provider_config",
        ["dpa_document_id"],
        unique=False,
    )
    op.create_table(
        "ai_example",
        sa.Column(
            "task",
            sa.Enum(
                "extract_contacts",
                "extract_property",
                "classify_email",
                "propose_posting",
                "extract_invoice",
                "draft_reply",
                "check_statement",
                "answer_question",
                "summarize",
                name="ai_task",
            ),
            nullable=False,
        ),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["ai_proposal.id"],
            name=op.f("fk_ai_example_proposal_id_ai_proposal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_example_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_example")),
    )
    op.create_index(op.f("ix_ai_example_proposal_id"), "ai_example", ["proposal_id"], unique=False)
    op.create_index(op.f("ix_ai_example_task"), "ai_example", ["task"], unique=False)
    op.create_table(
        "ai_message",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("document_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("task_run_id", sa.UUID(), nullable=True),
        sa.Column("proposal_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversation.id"],
            name=op.f("fk_ai_message_conversation_id_ai_conversation"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["ai_proposal.id"],
            name=op.f("fk_ai_message_proposal_id_ai_proposal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["ai_task_run.id"],
            name=op.f("fk_ai_message_task_run_id_ai_task_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_ai_message_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_message")),
    )
    op.create_index(
        op.f("ix_ai_message_conversation_id"), "ai_message", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_ai_message_proposal_id"), "ai_message", ["proposal_id"], unique=False)
    op.create_index(op.f("ix_ai_message_task_run_id"), "ai_message", ["task_run_id"], unique=False)
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_message_task_run_id"), table_name="ai_message")
    op.drop_index(op.f("ix_ai_message_proposal_id"), table_name="ai_message")
    op.drop_index(op.f("ix_ai_message_conversation_id"), table_name="ai_message")
    op.drop_table("ai_message")
    op.drop_index(op.f("ix_ai_example_task"), table_name="ai_example")
    op.drop_index(op.f("ix_ai_example_proposal_id"), table_name="ai_example")
    op.drop_table("ai_example")
    op.drop_index(op.f("ix_ai_provider_config_dpa_document_id"), table_name="ai_provider_config")
    op.drop_table("ai_provider_config")
    op.drop_index(op.f("ix_ai_proposal_task_run_id"), table_name="ai_proposal")
    op.drop_index(op.f("ix_ai_proposal_import_run_id"), table_name="ai_proposal")
    op.drop_table("ai_proposal")
    op.drop_index(op.f("ix_import_run_item_import_run_id"), table_name="import_run_item")
    op.drop_table("import_run_item")
    op.drop_index("ix_ai_task_run_input_hash", table_name="ai_task_run")
    op.drop_index(op.f("ix_ai_task_run_conversation_id"), table_name="ai_task_run")
    op.drop_table("ai_task_run")
    op.drop_table("import_run")
    op.drop_table("ai_conversation")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
