"""immoware24 import

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-23 10:58:31.474166+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TENANT_TABLES = ("import_mapping", "import_source_file", "import_staging_row")
ENUMS = ("import_report_type", "import_file_status", "import_row_status")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_mapping",
        sa.Column(
            "report_type",
            sa.Enum(
                "properties",
                "units",
                "contacts",
                "tenancies",
                "ownerships",
                "payments",
                "journal",
                "bank_transactions",
                name="import_report_type",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("columns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("value_maps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_import_mapping_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_mapping")),
        sa.UniqueConstraint(
            "tenant_id",
            "report_type",
            "name",
            "version",
            name=op.f("uq_import_mapping_tenant_id_report_type_name_version"),
        ),
    )
    op.create_table(
        "import_source_file",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum(
                "properties",
                "units",
                "contacts",
                "tenancies",
                "ownerships",
                "payments",
                "journal",
                "bank_transactions",
                name="import_report_type",
            ),
            nullable=False,
        ),
        sa.Column("sheet", sa.String(length=100), nullable=True),
        sa.Column("header_row", sa.Integer(), nullable=False),
        sa.Column("headers", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("mapping_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("uploaded", "mapped", "validated", "applied", name="import_file_status"),
            nullable=False,
        ),
        sa.Column("import_run_id", sa.UUID(), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_import_source_file_document_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_run.id"],
            name=op.f("fk_import_source_file_import_run_id_import_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["import_mapping.id"],
            name=op.f("fk_import_source_file_mapping_id_import_mapping"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_import_source_file_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_source_file")),
    )
    op.create_table(
        "import_staging_row",
        sa.Column("source_file_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "valid",
                "invalid",
                "unchanged",
                "conflict",
                "created",
                "staged_only",
                name="import_row_status",
            ),
            nullable=False,
        ),
        sa.Column("errors", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("entity_type", sa.String(length=63), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["import_source_file.id"],
            name=op.f("fk_import_staging_row_source_file_id_import_source_file"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_import_staging_row_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_staging_row")),
        sa.UniqueConstraint(
            "tenant_id",
            "source_file_id",
            "row_number",
            name=op.f("uq_import_staging_row_tenant_id_source_file_id_row_number"),
        ),
    )
    op.create_index(
        op.f("ix_import_staging_row_source_file_id"),
        "import_staging_row",
        ["source_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_import_staging_row_source_file_id"), table_name="import_staging_row")
    op.drop_table("import_staging_row")
    op.drop_table("import_source_file")
    op.drop_table("import_mapping")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
