"""banking

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-23 15:22:11.614099+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("bank_connection", "bank_sync_run", "bank_statement", "bank_transaction")
ENUMS = ("bank_connection_status", "bank_connector", "bank_transaction_status")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_connection",
        sa.Column(
            "connector",
            sa.Enum(
                "ebics",
                "aggregator_finapi",
                "aggregator_gocardless",
                "fints",
                "file_import",
                name="bank_connector",
            ),
            nullable=False,
        ),
        sa.Column("bank_name", sa.String(length=200), nullable=False),
        sa.Column("bic", sa.String(length=11), nullable=True),
        sa.Column("credentials", sa.LargeBinary(), nullable=True),
        sa.Column("consent_valid_until", sa.Date(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_schedule", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_configured",
                "active",
                "error",
                "consent_expired",
                "disabled",
                name="bank_connection_status",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_bank_connection_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_connection")),
    )
    op.create_table(
        "bank_sync_run",
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column("property_bank_account_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["bank_connection.id"],
            name=op.f("fk_bank_sync_run_connection_id_bank_connection"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_bank_sync_run_document_id_document")
        ),
        sa.ForeignKeyConstraint(
            ["property_bank_account_id"],
            ["property_bank_account.id"],
            name=op.f("fk_bank_sync_run_property_bank_account_id_property_bank_account"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_bank_sync_run_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_sync_run")),
    )
    op.create_table(
        "bank_statement",
        sa.Column("property_bank_account_id", sa.UUID(), nullable=False),
        sa.Column("sync_run_id", sa.UUID(), nullable=True),
        sa.Column("statement_ref", sa.String(length=100), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=True),
        sa.Column("to_date", sa.Date(), nullable=True),
        sa.Column("opening_balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("closing_balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("closing_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_bank_account_id"],
            ["property_bank_account.id"],
            name=op.f("fk_bank_statement_property_bank_account_id_property_bank_account"),
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["bank_sync_run.id"],
            name=op.f("fk_bank_statement_sync_run_id_bank_sync_run"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_bank_statement_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_statement")),
    )
    op.create_index(
        "uq_bank_statement_ref",
        "bank_statement",
        ["tenant_id", "property_bank_account_id", "statement_ref"],
        unique=True,
    )
    op.create_table(
        "bank_transaction",
        sa.Column("property_bank_account_id", sa.UUID(), nullable=False),
        sa.Column("legal_entity_id", sa.UUID(), nullable=False),
        sa.Column("statement_id", sa.UUID(), nullable=True),
        sa.Column("sync_run_id", sa.UUID(), nullable=True),
        sa.Column("bank_reference", sa.String(length=140), nullable=True),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("counterpart_name", sa.String(length=200), nullable=True),
        sa.Column("counterpart_iban", sa.LargeBinary(), nullable=True),
        sa.Column("counterpart_iban_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("counterpart_bic", sa.String(length=11), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("end_to_end_id", sa.String(length=140), nullable=True),
        sa.Column("mandate_reference", sa.String(length=140), nullable=True),
        sa.Column("creditor_id", sa.String(length=64), nullable=True),
        sa.Column("transaction_code", sa.String(length=64), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("possible_duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("transfer_pair_id", sa.UUID(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "needs_review",
                "proposed",
                "booked",
                "ignored",
                "split",
                name="bank_transaction_status",
            ),
            nullable=False,
        ),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("ai_proposal_id", sa.UUID(), nullable=True),
        sa.Column("matched_rule_id", sa.UUID(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_proposal_id"],
            ["ai_proposal.id"],
            name=op.f("fk_bank_transaction_ai_proposal_id_ai_proposal"),
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_bank_transaction_journal_entry_id_journal_entry"),
        ),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entity.id"],
            name=op.f("fk_bank_transaction_legal_entity_id_legal_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["possible_duplicate_of_id"],
            ["bank_transaction.id"],
            name=op.f("fk_bank_transaction_possible_duplicate_of_id_bank_transaction"),
        ),
        sa.ForeignKeyConstraint(
            ["property_bank_account_id"],
            ["property_bank_account.id"],
            name=op.f("fk_bank_transaction_property_bank_account_id_property_bank_account"),
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["bank_statement.id"],
            name=op.f("fk_bank_transaction_statement_id_bank_statement"),
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["bank_sync_run.id"],
            name=op.f("fk_bank_transaction_sync_run_id_bank_sync_run"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_bank_transaction_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_pair_id"],
            ["bank_transaction.id"],
            name=op.f("fk_bank_transaction_transfer_pair_id_bank_transaction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_transaction")),
    )
    op.create_index(
        op.f("ix_bank_transaction_counterpart_iban_fingerprint"),
        "bank_transaction",
        ["counterpart_iban_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_bank_transaction_hash",
        "bank_transaction",
        ["tenant_id", "property_bank_account_id", "hash"],
        unique=False,
    )
    op.create_index(
        "uq_bank_transaction_reference",
        "bank_transaction",
        ["tenant_id", "property_bank_account_id", "bank_reference"],
        unique=True,
        postgresql_where=sa.text("bank_reference IS NOT NULL"),
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_bank_transaction_reference",
        table_name="bank_transaction",
        postgresql_where=sa.text("bank_reference IS NOT NULL"),
    )
    op.drop_index("ix_bank_transaction_hash", table_name="bank_transaction")
    op.drop_index(
        op.f("ix_bank_transaction_counterpart_iban_fingerprint"), table_name="bank_transaction"
    )
    op.drop_table("bank_transaction")
    op.drop_index("uq_bank_statement_ref", table_name="bank_statement")
    op.drop_table("bank_statement")
    op.drop_table("bank_sync_run")
    op.drop_table("bank_connection")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
