"""receivables

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-23 15:34:04.999531+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("receivable_run", "admin_fee_setting", "payment_type_account", "receivable_item")
ENUMS = ("receivable_item_status", "receivable_run_status")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receivable_run",
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("preview", "posted", "reversed", name="receivable_run_status"),
            nullable=False,
        ),
        sa.Column("preview_hash", sa.String(length=64), nullable=False),
        sa.Column("totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_receivable_run_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivable_run")),
    )
    op.create_table(
        "admin_fee_setting",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("contract_document_id", sa.UUID(), nullable=True),
        sa.Column("invoice_debtor_party_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("interval", sa.String(length=16), nullable=False),
        sa.Column("vat_percent", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("min_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("max_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("amounts_per_unit_type", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_document_id"],
            ["document.id"],
            name=op.f("fk_admin_fee_setting_contract_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_debtor_party_id"],
            ["party.id"],
            name=op.f("fk_admin_fee_setting_invoice_debtor_party_id_party"),
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
            name=op.f("fk_admin_fee_setting_property_id_property"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_admin_fee_setting_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_fee_setting")),
    )
    op.create_table(
        "payment_type_account",
        sa.Column("ledger_id", sa.UUID(), nullable=False),
        sa.Column("payment_type_code", sa.String(length=63), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ledger_account.id"],
            name=op.f("fk_payment_type_account_account_id_ledger_account"),
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["ledger.id"],
            name=op.f("fk_payment_type_account_ledger_id_ledger"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_payment_type_account_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_type_account")),
        sa.UniqueConstraint(
            "tenant_id",
            "ledger_id",
            "payment_type_code",
            name=op.f("uq_payment_type_account_tenant_id_ledger_id_payment_type_code"),
        ),
    )
    op.create_table(
        "receivable_item",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("contract_payment_id", sa.UUID(), nullable=True),
        sa.Column("ledger_id", sa.UUID(), nullable=True),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("payment_type_code", sa.String(length=63), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vat_percent", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ready", "manual", "blocked", "posted", "reversed", name="receivable_item_status"
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_receivable_item_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["contract_payment_id"],
            ["contract_payment.id"],
            name=op.f("fk_receivable_item_contract_payment_id_contract_payment"),
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_receivable_item_journal_entry_id_journal_entry"),
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"], ["ledger.id"], name=op.f("fk_receivable_item_ledger_id_ledger")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["receivable_run.id"],
            name=op.f("fk_receivable_item_run_id_receivable_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_receivable_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivable_item")),
    )
    op.create_index(
        "uq_receivable_item_posted",
        "receivable_item",
        ["tenant_id", "contract_id", "payment_type_code", "period_month"],
        unique=True,
        postgresql_where=sa.text("status = 'posted'"),
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_receivable_item_posted",
        table_name="receivable_item",
        postgresql_where=sa.text("status = 'posted'"),
    )
    op.drop_table("receivable_item")
    op.drop_table("payment_type_account")
    op.drop_table("admin_fee_setting")
    op.drop_table("receivable_run")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
