"""payments

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-23 15:47:53.553131+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("payment_batch", "payment_order", "payment_approval")
ENUMS = ("payment_order_status",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_batch",
        sa.Column("property_bank_account_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.String(length=35), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("submitted_via", sa.String(length=16), nullable=True),
        sa.Column("bank_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_payment_batch_document_id_document")
        ),
        sa.ForeignKeyConstraint(
            ["property_bank_account_id"],
            ["property_bank_account.id"],
            name=op.f("fk_payment_batch_property_bank_account_id_property_bank_account"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_payment_batch_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_batch")),
        sa.UniqueConstraint("message_id", name=op.f("uq_payment_batch_message_id")),
    )
    op.create_table(
        "payment_order",
        sa.Column("ledger_id", sa.UUID(), nullable=False),
        sa.Column("property_bank_account_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column("open_item_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("counterpart_name", sa.String(length=140), nullable=False),
        sa.Column("counterpart_iban", sa.LargeBinary(), nullable=False),
        sa.Column("counterpart_iban_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=140), nullable=False),
        sa.Column("end_to_end_id", sa.String(length=35), nullable=False),
        sa.Column("execution_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "approved",
                "exported",
                "submitted",
                "accepted_by_bank",
                "executed",
                "partially_executed",
                "rejected",
                "returned",
                "cancelled",
                name="payment_order_status",
            ),
            nullable=False,
        ),
        sa.Column("executed_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("bank_transaction_id", sa.UUID(), nullable=True),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transaction.id"],
            name=op.f("fk_payment_order_bank_transaction_id_bank_transaction"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["payment_batch.id"], name=op.f("fk_payment_order_batch_id_payment_batch")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoice.id"], name=op.f("fk_payment_order_invoice_id_invoice")
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_payment_order_journal_entry_id_journal_entry"),
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"], ["ledger.id"], name=op.f("fk_payment_order_ledger_id_ledger")
        ),
        sa.ForeignKeyConstraint(
            ["open_item_id"], ["open_item.id"], name=op.f("fk_payment_order_open_item_id_open_item")
        ),
        sa.ForeignKeyConstraint(
            ["property_bank_account_id"],
            ["property_bank_account.id"],
            name=op.f("fk_payment_order_property_bank_account_id_property_bank_account"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_payment_order_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_order")),
    )
    op.create_table(
        "payment_approval",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["payment_order.id"],
            name=op.f("fk_payment_approval_order_id_payment_order"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_payment_approval_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_approval")),
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_approval")
    op.drop_table("payment_order")
    op.drop_table("payment_batch")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
