"""dunning

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-23 15:53:17.528131+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("dunning_run", "dunning_settings", "dunning_case")
ENUMS = ()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dunning_run",
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_dunning_run_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dunning_run")),
    )
    op.create_table(
        "dunning_settings",
        sa.Column("property_id", sa.UUID(), nullable=True),
        sa.Column("levels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("threshold_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"], ["property.id"], name=op.f("fk_dunning_settings_property_id_property")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_dunning_settings_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dunning_settings")),
    )
    op.create_index(
        "uq_dunning_settings_scope",
        "dunning_settings",
        [
            "tenant_id",
            sa.literal_column(
                "coalesce(property_id, '00000000-0000-0000-0000-000000000000'::uuid)"
            ),
        ],
        unique=True,
    )
    op.create_table(
        "dunning_case",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("ledger_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=True),
        sa.Column("debtor_account_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("open_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("fee_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("interest_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("letter_document_id", sa.UUID(), nullable=True),
        sa.Column("delivery_channel", sa.String(length=16), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_dunning_case_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["debtor_account_id"],
            ["ledger_account.id"],
            name=op.f("fk_dunning_case_debtor_account_id_ledger_account"),
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"], ["ledger.id"], name=op.f("fk_dunning_case_ledger_id_ledger")
        ),
        sa.ForeignKeyConstraint(
            ["letter_document_id"],
            ["document.id"],
            name=op.f("fk_dunning_case_letter_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["dunning_run.id"],
            name=op.f("fk_dunning_case_run_id_dunning_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_dunning_case_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dunning_case")),
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dunning_case")
    op.drop_index("uq_dunning_settings_scope", table_name="dunning_settings")
    op.drop_table("dunning_settings")
    op.drop_table("dunning_run")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
