"""hoa

Revision ID: 0022
Revises: 0021
Create Date: 2026-09-23 16:38:45.290254+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "resolution",
    "economic_plan",
    "hoa_statement",
    "owners_meeting",
    "audit_engagement",
    "meeting_agenda_item",
    "audit_report",
    "meeting_attendance",
    "meeting_vote",
    "audit_item",
    "economic_plan_item",
    "hoa_cost_item",
)
ENUMS: tuple[str, ...] = ()  # statement_status belongs to 0014


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resolution",
        sa.Column("legal_entity_id", sa.UUID(), nullable=False),
        sa.Column("meeting_id", sa.UUID(), nullable=True),
        sa.Column("agenda_item_id", sa.UUID(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("decided_on", sa.Date(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("wording", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("subject_type", sa.String(length=32), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("votes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("majority_basis", sa.Text(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_resolution_document_id_document")
        ),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entity.id"],
            name=op.f("fk_resolution_legal_entity_id_legal_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_resolution_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution")),
    )
    op.create_table(
        "economic_plan",
        sa.Column("ledger_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "calculated",
                "internally_approved",
                "board_reviewed",
                "resolved",
                "issued",
                "due",
                "posted",
                "locked",
                name="statement_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("resolution_id", sa.UUID(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ledger_id"], ["ledger.id"], name=op.f("fk_economic_plan_ledger_id_ledger")
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["resolution.id"],
            name=op.f("fk_economic_plan_resolution_id_resolution"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["economic_plan.id"],
            name=op.f("fk_economic_plan_supersedes_id_economic_plan"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_economic_plan_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_economic_plan")),
    )
    op.create_table(
        "hoa_statement",
        sa.Column("ledger_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "calculated",
                "internally_approved",
                "board_reviewed",
                "resolved",
                "issued",
                "due",
                "posted",
                "locked",
                name="statement_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("reserve_opening", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reserve_withdrawals", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reserve_interest", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("addressing_rule_version", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("resolution_id", sa.UUID(), nullable=True),
        sa.Column("posted_entry_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ledger_id"], ["ledger.id"], name=op.f("fk_hoa_statement_ledger_id_ledger")
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["resolution.id"],
            name=op.f("fk_hoa_statement_resolution_id_resolution"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["hoa_statement.id"],
            name=op.f("fk_hoa_statement_supersedes_id_hoa_statement"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_hoa_statement_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hoa_statement")),
    )
    op.create_table(
        "owners_meeting",
        sa.Column("legal_entity_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("invited_at", sa.Date(), nullable=True),
        sa.Column("voting_principle", sa.String(length=16), nullable=False),
        sa.Column("voting_principle_basis", sa.Text(), nullable=True),
        sa.Column("virtual_basis_resolution_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("chair_user_id", sa.UUID(), nullable=True),
        sa.Column("minutes_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entity.id"],
            name=op.f("fk_owners_meeting_legal_entity_id_legal_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["minutes_document_id"],
            ["document.id"],
            name=op.f("fk_owners_meeting_minutes_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_owners_meeting_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["virtual_basis_resolution_id"],
            ["resolution.id"],
            name=op.f("fk_owners_meeting_virtual_basis_resolution_id_resolution"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owners_meeting")),
    )
    op.create_table(
        "audit_engagement",
        sa.Column("legal_entity_id", sa.UUID(), nullable=False),
        sa.Column("statement_id", sa.UUID(), nullable=True),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("period_from", sa.Date(), nullable=False),
        sa.Column("period_to", sa.Date(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("auditor_contact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sampling", sa.String(length=16), nullable=False),
        sa.Column("population", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entity.id"],
            name=op.f("fk_audit_engagement_legal_entity_id_legal_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["hoa_statement.id"],
            name=op.f("fk_audit_engagement_statement_id_hoa_statement"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_audit_engagement_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_engagement")),
    )
    op.create_table(
        "meeting_agenda_item",
        sa.Column("meeting_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("proposal", sa.Text(), nullable=True),
        sa.Column("majority", sa.String(length=32), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["owners_meeting.id"],
            name=op.f("fk_meeting_agenda_item_meeting_id_owners_meeting"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_meeting_agenda_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_agenda_item")),
    )
    op.create_table(
        "audit_report",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["audit_engagement.id"],
            name=op.f("fk_audit_report_engagement_id_audit_engagement"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_audit_report_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_report")),
    )
    op.create_table(
        "meeting_attendance",
        sa.Column("meeting_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("proxy_contact_id", sa.UUID(), nullable=True),
        sa.Column("proxy_document_id", sa.UUID(), nullable=True),
        sa.Column("online", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.id"],
            name=op.f("fk_meeting_attendance_contract_id_contract"),
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["owners_meeting.id"],
            name=op.f("fk_meeting_attendance_meeting_id_owners_meeting"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proxy_contact_id"],
            ["contact.id"],
            name=op.f("fk_meeting_attendance_proxy_contact_id_contact"),
        ),
        sa.ForeignKeyConstraint(
            ["proxy_document_id"],
            ["document.id"],
            name=op.f("fk_meeting_attendance_proxy_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_meeting_attendance_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_attendance")),
    )
    op.create_table(
        "meeting_vote",
        sa.Column("agenda_item_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("choice", sa.String(length=8), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agenda_item_id"],
            ["meeting_agenda_item.id"],
            name=op.f("fk_meeting_vote_agenda_item_id_meeting_agenda_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_meeting_vote_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_meeting_vote_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_vote")),
    )
    op.create_table(
        "audit_item",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_audit_item_document_id_document")
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["audit_engagement.id"],
            name=op.f("fk_audit_item_engagement_id_audit_engagement"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entry.id"],
            name=op.f("fk_audit_item_journal_entry_id_journal_entry"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_audit_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_item")),
    )
    op.create_table(
        "economic_plan_item",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("component", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("allocation_key_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ledger_account.id"],
            name=op.f("fk_economic_plan_item_account_id_ledger_account"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_key_id"],
            ["allocation_key.id"],
            name=op.f("fk_economic_plan_item_allocation_key_id_allocation_key"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["economic_plan.id"],
            name=op.f("fk_economic_plan_item_plan_id_economic_plan"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_economic_plan_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_economic_plan_item")),
    )
    op.create_table(
        "hoa_cost_item",
        sa.Column("statement_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("allocation_key_id", sa.UUID(), nullable=False),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ledger_account.id"],
            name=op.f("fk_hoa_cost_item_account_id_ledger_account"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_key_id"],
            ["allocation_key.id"],
            name=op.f("fk_hoa_cost_item_allocation_key_id_allocation_key"),
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["hoa_statement.id"],
            name=op.f("fk_hoa_cost_item_statement_id_hoa_statement"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_hoa_cost_item_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hoa_cost_item")),
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hoa_cost_item")
    op.drop_table("economic_plan_item")
    op.drop_table("audit_item")
    op.drop_table("meeting_vote")
    op.drop_table("meeting_attendance")
    op.drop_table("audit_report")
    op.drop_table("meeting_agenda_item")
    op.drop_table("audit_engagement")
    op.drop_table("owners_meeting")
    op.drop_table("hoa_statement")
    op.drop_table("economic_plan")
    op.drop_table("resolution")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
