"""letting

Revision ID: 0023
Revises: 0022
Create Date: 2026-09-23 16:59:38.363654+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("prospect", "rent_increase_case")
ENUMS = ()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prospect",
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("viewing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("delete_after", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contact.id"], name=op.f("fk_prospect_contact_id_contact")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_prospect_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["unit.id"], name=op.f("fk_prospect_unit_id_unit"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect")),
    )
    op.create_table(
        "rent_increase_case",
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("basis", sa.String(length=16), nullable=False),
        sa.Column("current_rent", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("target_rent", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reference_rent", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("cap_limit_percent", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("comparison_rent_per_sqm", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("living_area_sqm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("source_note", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("earliest_effective_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("check", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("legal_review_document_id", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_document_id", sa.UUID(), nullable=True),
        sa.Column("new_payment_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consent_document_id"],
            ["document.id"],
            name=op.f("fk_rent_increase_case_consent_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.id"],
            name=op.f("fk_rent_increase_case_contract_id_contract"),
        ),
        sa.ForeignKeyConstraint(
            ["legal_review_document_id"],
            ["document.id"],
            name=op.f("fk_rent_increase_case_legal_review_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["new_payment_id"],
            ["contract_payment.id"],
            name=op.f("fk_rent_increase_case_new_payment_id_contract_payment"),
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["document.id"],
            name=op.f("fk_rent_increase_case_source_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_rent_increase_case_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rent_increase_case")),
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rent_increase_case")
    op.drop_table("prospect")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
