"""invoice_recipient

Revision ID: 0026
Revises: 0025
Create Date: 2026-09-24 08:30:24.534284+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0026"
down_revision: str | None = "0025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES: tuple[str, ...] = ()
ENUMS: tuple[str, ...] = ()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("recipient_name", sa.String(length=400), nullable=True))
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice", "recipient_name")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
