"""majority_rule

Revision ID: 0027
Revises: 0026
Create Date: 2026-09-24 18:56:46.021404+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0027"
down_revision: str | None = "0026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("majority_rule",)
ENUMS: tuple[str, ...] = ()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "majority_rule",
        sa.Column("legal_entity_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("principle", sa.String(length=16), nullable=False),
        sa.Column("share_of_votes_cast", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("strictly_greater", sa.Boolean(), nullable=False),
        sa.Column("min_mea_share_of_all", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("unanimous", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entity.id"],
            name=op.f("fk_majority_rule_legal_entity_id_legal_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_majority_rule_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_majority_rule")),
    )
    op.add_column("meeting_agenda_item", sa.Column("rule_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_meeting_agenda_item_rule_id_majority_rule"),
        "meeting_agenda_item",
        "majority_rule",
        ["rule_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_meeting_agenda_item_rule_id_majority_rule"),
        "meeting_agenda_item",
        type_="foreignkey",
    )
    op.drop_column("meeting_agenda_item", "rule_id")
    op.drop_table("majority_rule")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
