"""levy_versions

Revision ID: 0028
Revises: 0027
Create Date: 2026-09-24 19:03:17.229707+00:00

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0028"
down_revision: str | None = "0027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES: tuple[str, ...] = ()
ENUMS: tuple[str, ...] = ()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "special_levy",
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    op.add_column("special_levy", sa.Column("supersedes_id", sa.UUID(), nullable=True))
    op.add_column("special_levy", sa.Column("difference_due", sa.Date(), nullable=True))
    op.add_column("special_levy", sa.Column("change_reason", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_special_levy_supersedes_id_special_levy"),
        "special_levy",
        "special_levy",
        ["supersedes_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_special_levy_supersedes_id_special_levy"), "special_levy", type_="foreignkey"
    )
    op.drop_column("special_levy", "change_reason")
    op.drop_column("special_levy", "difference_due")
    op.drop_column("special_levy", "supersedes_id")
    op.drop_column("special_levy", "version")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
