"""sla_module: SLA-Regeln, Uhren, Eskalation, Bereitschaft und Notfallalarme (M21,
Übernahme aus dem Immoware Hub, docs/mail/04-status-und-sla.md).

Revision ID: 0042
Revises: 0041

Tenant tables must call mhvp.core.db.rls.tenant_rls_statements() (ADR 0002).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mhvp.core.db.rls import drop_tenant_rls_statements, tenant_rls_statements

revision: str = "0042"
down_revision: str | None = "0041"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "sla_rule",
    "sla_escalation_step",
    "sla_clock",
    "sla_clock_log",
    "sla_on_call_schedule",
    "sla_emergency_alert",
    "sla_work_calendar",
)
ENUMS = (
    "sla_clock_type",
    "sla_clock_state",
    "sla_color",
    "sla_alert_channel",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sla_on_call_schedule",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phone", sa.LargeBinary(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sla_on_call_schedule_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_on_call_schedule")),
    )
    op.create_table(
        "sla_rule",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "low",
                "normal",
                "high",
                "urgent",
                "immediate",
                name="ticket_priority",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("response_minutes", sa.Integer(), nullable=False),
        sa.Column("resolution_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "clock_type", sa.Enum("business", "calendar", name="sla_clock_type"), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sla_rule_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_rule")),
        sa.UniqueConstraint("tenant_id", "priority", name=op.f("uq_sla_rule_tenant_id_priority")),
    )
    op.create_table(
        "sla_work_calendar",
        sa.Column("weekdays", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=False),
        sa.Column("closes_at", sa.Time(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("holidays", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sla_work_calendar_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_work_calendar")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_sla_work_calendar_tenant_id")),
    )
    op.create_table(
        "sla_escalation_step",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("after_minutes", sa.Integer(), nullable=False),
        sa.Column("notify_user_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("notify_role", sa.String(length=64), nullable=True),
        sa.Column(
            "channel", sa.Enum("email", "internal", name="sla_alert_channel"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["sla_rule.id"],
            name=op.f("fk_sla_escalation_step_rule_id_sla_rule"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sla_escalation_step_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_escalation_step")),
        sa.UniqueConstraint(
            "rule_id", "step_no", name=op.f("uq_sla_escalation_step_rule_id_step_no")
        ),
    )
    op.create_table(
        "sla_clock",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_minutes_total", sa.Integer(), nullable=False),
        sa.Column("due_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_resolution_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state",
            sa.Enum("running", "paused", "breached", "done", name="sla_clock_state"),
            nullable=False,
        ),
        sa.Column("color", sa.Enum("green", "yellow", "red", name="sla_color"), nullable=False),
        sa.Column("escalated_steps", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["sla_rule.id"], name=op.f("fk_sla_clock_rule_id_sla_rule")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sla_clock_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
            name=op.f("fk_sla_clock_ticket_id_ticket"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_clock")),
        sa.UniqueConstraint("ticket_id", name=op.f("uq_sla_clock_ticket_id")),
    )
    op.create_table(
        "sla_emergency_alert",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("sent_to", sa.String(length=300), nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM("email", "internal", name="sla_alert_channel", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sla_emergency_alert_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
            name=op.f("fk_sla_emergency_alert_ticket_id_ticket"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_emergency_alert")),
    )
    op.create_table(
        "sla_clock_log",
        sa.Column("clock_id", sa.UUID(), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clock_id"],
            ["sla_clock.id"],
            name=op.f("fk_sla_clock_log_clock_id_sla_clock"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sla_clock_log_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_clock_log")),
    )
    # ### end Alembic commands ###
    for table in TENANT_TABLES:
        for statement in tenant_rls_statements(table):
            op.execute(statement)


def downgrade() -> None:
    for table in reversed(TENANT_TABLES):
        for statement in drop_tenant_rls_statements(table):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sla_clock_log")
    op.drop_table("sla_emergency_alert")
    op.drop_table("sla_clock")
    op.drop_table("sla_escalation_step")
    op.drop_table("sla_work_calendar")
    op.drop_table("sla_rule")
    op.drop_table("sla_on_call_schedule")
    # ### end Alembic commands ###
    for enum in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
